# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: thorchain/v1/x/thorchain/types/misc.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)thorchain/v1/x/thorchain/types/misc.proto\x12\x05types\x1a\x14gogoproto/gogo.proto\"\x1b\n\nProtoInt64\x12\r\n\x05value\x18\x01 \x01(\x03\"\x1c\n\x0bProtoUint64\x12\r\n\x05value\x18\x01 \x01(\x04\"U\n\x11ProtoAccAddresses\x12@\n\x05value\x18\x01 \x03(\x0c\x42\x31\xfa\xde\x1f-github.com/cosmos/cosmos-sdk/types.AccAddress\"\x1d\n\x0cProtoStrings\x12\r\n\x05value\x18\x01 \x03(\t\"\x1b\n\nProtoBools\x12\r\n\x05value\x18\x01 \x03(\x08\x42\x31Z/gitlab.com/thorchain/thornode/x/thorchain/typesb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'thorchain.v1.x.thorchain.types.misc_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z/gitlab.com/thorchain/thornode/x/thorchain/types'
  _PROTOACCADDRESSES.fields_by_name['value']._options = None
  _PROTOACCADDRESSES.fields_by_name['value']._serialized_options = b'\372\336\037-github.com/cosmos/cosmos-sdk/types.AccAddress'
  _PROTOINT64._serialized_start=74
  _PROTOINT64._serialized_end=101
  _PROTOUINT64._serialized_start=103
  _PROTOUINT64._serialized_end=131
  _PROTOACCADDRESSES._serialized_start=133
  _PROTOACCADDRESSES._serialized_end=218
  _PROTOSTRINGS._serialized_start=220
  _PROTOSTRINGS._serialized_end=249
  _PROTOBOOLS._serialized_start=251
  _PROTOBOOLS._serialized_end=278
# @@protoc_insertion_point(module_scope)
