"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys
import thorchain.v1.common.common_pb2

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class MsgLoanOpen(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OWNER_FIELD_NUMBER: builtins.int
    COLLATERAL_ASSET_FIELD_NUMBER: builtins.int
    COLLATERAL_AMOUNT_FIELD_NUMBER: builtins.int
    TARGET_ADDRESS_FIELD_NUMBER: builtins.int
    TARGET_ASSET_FIELD_NUMBER: builtins.int
    MIN_OUT_FIELD_NUMBER: builtins.int
    AFFILIATE_ADDRESS_FIELD_NUMBER: builtins.int
    AFFILIATE_BASIS_POINTS_FIELD_NUMBER: builtins.int
    AGGREGATOR_FIELD_NUMBER: builtins.int
    AGGREGATOR_TARGET_ADDRESS_FIELD_NUMBER: builtins.int
    AGGREGATOR_TARGET_LIMIT_FIELD_NUMBER: builtins.int
    SIGNER_FIELD_NUMBER: builtins.int
    owner: builtins.str
    @property
    def collateral_asset(self) -> thorchain.v1.common.common_pb2.Asset: ...
    collateral_amount: builtins.str
    target_address: builtins.str
    @property
    def target_asset(self) -> thorchain.v1.common.common_pb2.Asset: ...
    min_out: builtins.str
    affiliate_address: builtins.str
    affiliate_basis_points: builtins.str
    aggregator: builtins.str
    aggregator_target_address: builtins.str
    aggregator_target_limit: builtins.str
    signer: builtins.bytes
    def __init__(
        self,
        *,
        owner: builtins.str = ...,
        collateral_asset: thorchain.v1.common.common_pb2.Asset | None = ...,
        collateral_amount: builtins.str = ...,
        target_address: builtins.str = ...,
        target_asset: thorchain.v1.common.common_pb2.Asset | None = ...,
        min_out: builtins.str = ...,
        affiliate_address: builtins.str = ...,
        affiliate_basis_points: builtins.str = ...,
        aggregator: builtins.str = ...,
        aggregator_target_address: builtins.str = ...,
        aggregator_target_limit: builtins.str = ...,
        signer: builtins.bytes = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["collateral_asset", b"collateral_asset", "target_asset", b"target_asset"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["affiliate_address", b"affiliate_address", "affiliate_basis_points", b"affiliate_basis_points", "aggregator", b"aggregator", "aggregator_target_address", b"aggregator_target_address", "aggregator_target_limit", b"aggregator_target_limit", "collateral_amount", b"collateral_amount", "collateral_asset", b"collateral_asset", "min_out", b"min_out", "owner", b"owner", "signer", b"signer", "target_address", b"target_address", "target_asset", b"target_asset"]) -> None: ...

global___MsgLoanOpen = MsgLoanOpen

@typing_extensions.final
class MsgLoanRepayment(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OWNER_FIELD_NUMBER: builtins.int
    COLLATERAL_ASSET_FIELD_NUMBER: builtins.int
    COIN_FIELD_NUMBER: builtins.int
    MIN_OUT_FIELD_NUMBER: builtins.int
    SIGNER_FIELD_NUMBER: builtins.int
    owner: builtins.str
    @property
    def collateral_asset(self) -> thorchain.v1.common.common_pb2.Asset: ...
    @property
    def coin(self) -> thorchain.v1.common.common_pb2.Coin: ...
    min_out: builtins.str
    signer: builtins.bytes
    def __init__(
        self,
        *,
        owner: builtins.str = ...,
        collateral_asset: thorchain.v1.common.common_pb2.Asset | None = ...,
        coin: thorchain.v1.common.common_pb2.Coin | None = ...,
        min_out: builtins.str = ...,
        signer: builtins.bytes = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["coin", b"coin", "collateral_asset", b"collateral_asset"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["coin", b"coin", "collateral_asset", b"collateral_asset", "min_out", b"min_out", "owner", b"owner", "signer", b"signer"]) -> None: ...

global___MsgLoanRepayment = MsgLoanRepayment
