"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class MsgBan(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NODE_ADDRESS_FIELD_NUMBER: builtins.int
    SIGNER_FIELD_NUMBER: builtins.int
    node_address: builtins.bytes
    signer: builtins.bytes
    def __init__(
        self,
        *,
        node_address: builtins.bytes = ...,
        signer: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["node_address", b"node_address", "signer", b"signer"]) -> None: ...

global___MsgBan = MsgBan
