"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys
import thorchain.v1.common.common_pb2

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class MsgWithdrawLiquidity(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TX_FIELD_NUMBER: builtins.int
    WITHDRAW_ADDRESS_FIELD_NUMBER: builtins.int
    BASIS_POINTS_FIELD_NUMBER: builtins.int
    ASSET_FIELD_NUMBER: builtins.int
    WITHDRAWAL_ASSET_FIELD_NUMBER: builtins.int
    SIGNER_FIELD_NUMBER: builtins.int
    @property
    def tx(self) -> thorchain.v1.common.common_pb2.Tx: ...
    withdraw_address: builtins.str
    basis_points: builtins.str
    @property
    def asset(self) -> thorchain.v1.common.common_pb2.Asset: ...
    @property
    def withdrawal_asset(self) -> thorchain.v1.common.common_pb2.Asset: ...
    signer: builtins.bytes
    def __init__(
        self,
        *,
        tx: thorchain.v1.common.common_pb2.Tx | None = ...,
        withdraw_address: builtins.str = ...,
        basis_points: builtins.str = ...,
        asset: thorchain.v1.common.common_pb2.Asset | None = ...,
        withdrawal_asset: thorchain.v1.common.common_pb2.Asset | None = ...,
        signer: builtins.bytes = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["asset", b"asset", "tx", b"tx", "withdrawal_asset", b"withdrawal_asset"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["asset", b"asset", "basis_points", b"basis_points", "signer", b"signer", "tx", b"tx", "withdraw_address", b"withdraw_address", "withdrawal_asset", b"withdrawal_asset"]) -> None: ...

global___MsgWithdrawLiquidity = MsgWithdrawLiquidity
