# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: thorchain/v1/x/thorchain/types/msg_swap.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from thorchain.v1.common import common_pb2 as thorchain_dot_v1_dot_common_dot_common__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-thorchain/v1/x/thorchain/types/msg_swap.proto\x12\x05types\x1a thorchain/v1/common/common.proto\x1a\x14gogoproto/gogo.proto\"\xf0\x04\n\x07MsgSwap\x12\x1c\n\x02tx\x18\x01 \x01(\x0b\x32\n.common.TxB\x04\xc8\xde\x1f\x00\x12)\n\x0ctarget_asset\x18\x02 \x01(\x0b\x32\r.common.AssetB\x04\xc8\xde\x1f\x00\x12\x45\n\x0b\x64\x65stination\x18\x03 \x01(\tB0\xfa\xde\x1f,gitlab.com/thorchain/thornode/common.Address\x12\x45\n\x0ctrade_target\x18\x04 \x01(\tB/\xda\xde\x1f\'github.com/cosmos/cosmos-sdk/types.Uint\xc8\xde\x1f\x00\x12K\n\x11\x61\x66\x66iliate_address\x18\x05 \x01(\tB0\xfa\xde\x1f,gitlab.com/thorchain/thornode/common.Address\x12O\n\x16\x61\x66\x66iliate_basis_points\x18\x06 \x01(\tB/\xda\xde\x1f\'github.com/cosmos/cosmos-sdk/types.Uint\xc8\xde\x1f\x00\x12\x41\n\x06signer\x18\x07 \x01(\x0c\x42\x31\xfa\xde\x1f-github.com/cosmos/cosmos-sdk/types.AccAddress\x12\x12\n\naggregator\x18\x08 \x01(\t\x12!\n\x19\x61ggregator_target_address\x18\t \x01(\t\x12P\n\x17\x61ggregator_target_limit\x18\n \x01(\tB/\xda\xde\x1f\'github.com/cosmos/cosmos-sdk/types.Uint\xc8\xde\x1f\x01\x12$\n\norder_type\x18\x0b \x01(\x0e\x32\x10.types.OrderType*\"\n\tOrderType\x12\n\n\x06market\x10\x00\x12\t\n\x05limit\x10\x01\x42\x31Z/gitlab.com/thorchain/thornode/x/thorchain/typesb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'thorchain.v1.x.thorchain.types.msg_swap_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z/gitlab.com/thorchain/thornode/x/thorchain/types'
  _MSGSWAP.fields_by_name['tx']._options = None
  _MSGSWAP.fields_by_name['tx']._serialized_options = b'\310\336\037\000'
  _MSGSWAP.fields_by_name['target_asset']._options = None
  _MSGSWAP.fields_by_name['target_asset']._serialized_options = b'\310\336\037\000'
  _MSGSWAP.fields_by_name['destination']._options = None
  _MSGSWAP.fields_by_name['destination']._serialized_options = b'\372\336\037,gitlab.com/thorchain/thornode/common.Address'
  _MSGSWAP.fields_by_name['trade_target']._options = None
  _MSGSWAP.fields_by_name['trade_target']._serialized_options = b'\332\336\037\'github.com/cosmos/cosmos-sdk/types.Uint\310\336\037\000'
  _MSGSWAP.fields_by_name['affiliate_address']._options = None
  _MSGSWAP.fields_by_name['affiliate_address']._serialized_options = b'\372\336\037,gitlab.com/thorchain/thornode/common.Address'
  _MSGSWAP.fields_by_name['affiliate_basis_points']._options = None
  _MSGSWAP.fields_by_name['affiliate_basis_points']._serialized_options = b'\332\336\037\'github.com/cosmos/cosmos-sdk/types.Uint\310\336\037\000'
  _MSGSWAP.fields_by_name['signer']._options = None
  _MSGSWAP.fields_by_name['signer']._serialized_options = b'\372\336\037-github.com/cosmos/cosmos-sdk/types.AccAddress'
  _MSGSWAP.fields_by_name['aggregator_target_limit']._options = None
  _MSGSWAP.fields_by_name['aggregator_target_limit']._serialized_options = b'\332\336\037\'github.com/cosmos/cosmos-sdk/types.Uint\310\336\037\001'
  _ORDERTYPE._serialized_start=739
  _ORDERTYPE._serialized_end=773
  _MSGSWAP._serialized_start=113
  _MSGSWAP._serialized_end=737
# @@protoc_insertion_point(module_scope)
