"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys
import thorchain.v1.common.common_pb2

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class MsgSetNodeKeys(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PUB_KEY_SET_SET_FIELD_NUMBER: builtins.int
    VALIDATOR_CONS_PUB_KEY_FIELD_NUMBER: builtins.int
    SIGNER_FIELD_NUMBER: builtins.int
    @property
    def pub_key_set_set(self) -> thorchain.v1.common.common_pb2.PubKeySet: ...
    validator_cons_pub_key: builtins.str
    signer: builtins.bytes
    def __init__(
        self,
        *,
        pub_key_set_set: thorchain.v1.common.common_pb2.PubKeySet | None = ...,
        validator_cons_pub_key: builtins.str = ...,
        signer: builtins.bytes = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["pub_key_set_set", b"pub_key_set_set"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["pub_key_set_set", b"pub_key_set_set", "signer", b"signer", "validator_cons_pub_key", b"validator_cons_pub_key"]) -> None: ...

global___MsgSetNodeKeys = MsgSetNodeKeys
