"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys
import thorchain.v1.x.thorchain.types.type_blame_pb2
import thorchain.v1.x.thorchain.types.type_keygen_pb2

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class MsgTssPool(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    POOL_PUB_KEY_FIELD_NUMBER: builtins.int
    KEYGEN_TYPE_FIELD_NUMBER: builtins.int
    PUB_KEYS_FIELD_NUMBER: builtins.int
    HEIGHT_FIELD_NUMBER: builtins.int
    BLAME_FIELD_NUMBER: builtins.int
    CHAINS_FIELD_NUMBER: builtins.int
    SIGNER_FIELD_NUMBER: builtins.int
    KEYGEN_TIME_FIELD_NUMBER: builtins.int
    KEYSHARES_BACKUP_FIELD_NUMBER: builtins.int
    id: builtins.str
    pool_pub_key: builtins.str
    keygen_type: thorchain.v1.x.thorchain.types.type_keygen_pb2.KeygenType.ValueType
    @property
    def pub_keys(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    height: builtins.int
    @property
    def blame(self) -> thorchain.v1.x.thorchain.types.type_blame_pb2.Blame: ...
    @property
    def chains(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    signer: builtins.bytes
    keygen_time: builtins.int
    keyshares_backup: builtins.bytes
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        pool_pub_key: builtins.str = ...,
        keygen_type: thorchain.v1.x.thorchain.types.type_keygen_pb2.KeygenType.ValueType = ...,
        pub_keys: collections.abc.Iterable[builtins.str] | None = ...,
        height: builtins.int = ...,
        blame: thorchain.v1.x.thorchain.types.type_blame_pb2.Blame | None = ...,
        chains: collections.abc.Iterable[builtins.str] | None = ...,
        signer: builtins.bytes = ...,
        keygen_time: builtins.int = ...,
        keyshares_backup: builtins.bytes = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["blame", b"blame"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["blame", b"blame", "chains", b"chains", "height", b"height", "id", b"id", "keygen_time", b"keygen_time", "keygen_type", b"keygen_type", "keyshares_backup", b"keyshares_backup", "pool_pub_key", b"pool_pub_key", "pub_keys", b"pub_keys", "signer", b"signer"]) -> None: ...

global___MsgTssPool = MsgTssPool
