"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import thorchain.v1.common.common_pb2
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _OrderType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _OrderTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_OrderType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    market: _OrderType.ValueType  # 0
    limit: _OrderType.ValueType  # 1

class OrderType(_OrderType, metaclass=_OrderTypeEnumTypeWrapper): ...

market: OrderType.ValueType  # 0
limit: OrderType.ValueType  # 1
global___OrderType = OrderType

@typing_extensions.final
class MsgSwap(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TX_FIELD_NUMBER: builtins.int
    TARGET_ASSET_FIELD_NUMBER: builtins.int
    DESTINATION_FIELD_NUMBER: builtins.int
    TRADE_TARGET_FIELD_NUMBER: builtins.int
    AFFILIATE_ADDRESS_FIELD_NUMBER: builtins.int
    AFFILIATE_BASIS_POINTS_FIELD_NUMBER: builtins.int
    SIGNER_FIELD_NUMBER: builtins.int
    AGGREGATOR_FIELD_NUMBER: builtins.int
    AGGREGATOR_TARGET_ADDRESS_FIELD_NUMBER: builtins.int
    AGGREGATOR_TARGET_LIMIT_FIELD_NUMBER: builtins.int
    ORDER_TYPE_FIELD_NUMBER: builtins.int
    @property
    def tx(self) -> thorchain.v1.common.common_pb2.Tx: ...
    @property
    def target_asset(self) -> thorchain.v1.common.common_pb2.Asset: ...
    destination: builtins.str
    trade_target: builtins.str
    affiliate_address: builtins.str
    affiliate_basis_points: builtins.str
    signer: builtins.bytes
    aggregator: builtins.str
    aggregator_target_address: builtins.str
    aggregator_target_limit: builtins.str
    order_type: global___OrderType.ValueType
    def __init__(
        self,
        *,
        tx: thorchain.v1.common.common_pb2.Tx | None = ...,
        target_asset: thorchain.v1.common.common_pb2.Asset | None = ...,
        destination: builtins.str = ...,
        trade_target: builtins.str = ...,
        affiliate_address: builtins.str = ...,
        affiliate_basis_points: builtins.str = ...,
        signer: builtins.bytes = ...,
        aggregator: builtins.str = ...,
        aggregator_target_address: builtins.str = ...,
        aggregator_target_limit: builtins.str = ...,
        order_type: global___OrderType.ValueType = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["target_asset", b"target_asset", "tx", b"tx"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["affiliate_address", b"affiliate_address", "affiliate_basis_points", b"affiliate_basis_points", "aggregator", b"aggregator", "aggregator_target_address", b"aggregator_target_address", "aggregator_target_limit", b"aggregator_target_limit", "destination", b"destination", "order_type", b"order_type", "signer", b"signer", "target_asset", b"target_asset", "trade_target", b"trade_target", "tx", b"tx"]) -> None: ...

global___MsgSwap = MsgSwap
