"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys
import thorchain.v1.common.common_pb2

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class MsgAddLiquidity(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TX_FIELD_NUMBER: builtins.int
    ASSET_FIELD_NUMBER: builtins.int
    ASSET_AMOUNT_FIELD_NUMBER: builtins.int
    RUNE_AMOUNT_FIELD_NUMBER: builtins.int
    RUNE_ADDRESS_FIELD_NUMBER: builtins.int
    ASSET_ADDRESS_FIELD_NUMBER: builtins.int
    AFFILIATE_ADDRESS_FIELD_NUMBER: builtins.int
    AFFILIATE_BASIS_POINTS_FIELD_NUMBER: builtins.int
    SIGNER_FIELD_NUMBER: builtins.int
    @property
    def tx(self) -> thorchain.v1.common.common_pb2.Tx: ...
    @property
    def asset(self) -> thorchain.v1.common.common_pb2.Asset: ...
    asset_amount: builtins.str
    rune_amount: builtins.str
    rune_address: builtins.str
    asset_address: builtins.str
    affiliate_address: builtins.str
    affiliate_basis_points: builtins.str
    signer: builtins.bytes
    def __init__(
        self,
        *,
        tx: thorchain.v1.common.common_pb2.Tx | None = ...,
        asset: thorchain.v1.common.common_pb2.Asset | None = ...,
        asset_amount: builtins.str = ...,
        rune_amount: builtins.str = ...,
        rune_address: builtins.str = ...,
        asset_address: builtins.str = ...,
        affiliate_address: builtins.str = ...,
        affiliate_basis_points: builtins.str = ...,
        signer: builtins.bytes = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["asset", b"asset", "tx", b"tx"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["affiliate_address", b"affiliate_address", "affiliate_basis_points", b"affiliate_basis_points", "asset", b"asset", "asset_address", b"asset_address", "asset_amount", b"asset_amount", "rune_address", b"rune_address", "rune_amount", b"rune_amount", "signer", b"signer", "tx", b"tx"]) -> None: ...

global___MsgAddLiquidity = MsgAddLiquidity
