"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys
import thorchain.v1.common.common_pb2

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class MsgBond(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TX_IN_FIELD_NUMBER: builtins.int
    NODE_ADDRESS_FIELD_NUMBER: builtins.int
    BOND_FIELD_NUMBER: builtins.int
    BOND_ADDRESS_FIELD_NUMBER: builtins.int
    SIGNER_FIELD_NUMBER: builtins.int
    BOND_PROVIDER_ADDRESS_FIELD_NUMBER: builtins.int
    OPERATOR_FEE_FIELD_NUMBER: builtins.int
    @property
    def tx_in(self) -> thorchain.v1.common.common_pb2.Tx: ...
    node_address: builtins.bytes
    bond: builtins.str
    bond_address: builtins.str
    signer: builtins.bytes
    bond_provider_address: builtins.bytes
    operator_fee: builtins.int
    def __init__(
        self,
        *,
        tx_in: thorchain.v1.common.common_pb2.Tx | None = ...,
        node_address: builtins.bytes = ...,
        bond: builtins.str = ...,
        bond_address: builtins.str = ...,
        signer: builtins.bytes = ...,
        bond_provider_address: builtins.bytes = ...,
        operator_fee: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["tx_in", b"tx_in"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["bond", b"bond", "bond_address", b"bond_address", "bond_provider_address", b"bond_provider_address", "node_address", b"node_address", "operator_fee", b"operator_fee", "signer", b"signer", "tx_in", b"tx_in"]) -> None: ...

global___MsgBond = MsgBond
