"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys
import thorchain.v1.common.common_pb2

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class MsgManageTHORName(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    CHAIN_FIELD_NUMBER: builtins.int
    ADDRESS_FIELD_NUMBER: builtins.int
    COIN_FIELD_NUMBER: builtins.int
    EXPIRE_BLOCK_HEIGHT_FIELD_NUMBER: builtins.int
    PREFERRED_ASSET_FIELD_NUMBER: builtins.int
    OWNER_FIELD_NUMBER: builtins.int
    SIGNER_FIELD_NUMBER: builtins.int
    name: builtins.str
    chain: builtins.str
    address: builtins.str
    @property
    def coin(self) -> thorchain.v1.common.common_pb2.Coin: ...
    expire_block_height: builtins.int
    @property
    def preferred_asset(self) -> thorchain.v1.common.common_pb2.Asset: ...
    owner: builtins.bytes
    signer: builtins.bytes
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        chain: builtins.str = ...,
        address: builtins.str = ...,
        coin: thorchain.v1.common.common_pb2.Coin | None = ...,
        expire_block_height: builtins.int = ...,
        preferred_asset: thorchain.v1.common.common_pb2.Asset | None = ...,
        owner: builtins.bytes = ...,
        signer: builtins.bytes = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["coin", b"coin", "preferred_asset", b"preferred_asset"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["address", b"address", "chain", b"chain", "coin", b"coin", "expire_block_height", b"expire_block_height", "name", b"name", "owner", b"owner", "preferred_asset", b"preferred_asset", "signer", b"signer"]) -> None: ...

global___MsgManageTHORName = MsgManageTHORName
