# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: thorchain/v1/x/thorchain/types/msg_tss_keysign_fail.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from thorchain.v1.x.thorchain.types import type_blame_pb2 as thorchain_dot_v1_dot_x_dot_thorchain_dot_types_dot_type__blame__pb2
from thorchain.v1.common import common_pb2 as thorchain_dot_v1_dot_common_dot_common__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n9thorchain/v1/x/thorchain/types/msg_tss_keysign_fail.proto\x12\x05types\x1a/thorchain/v1/x/thorchain/types/type_blame.proto\x1a thorchain/v1/common/common.proto\x1a\x14gogoproto/gogo.proto\"\xbe\x02\n\x11MsgTssKeysignFail\x12\x12\n\x02id\x18\x01 \x01(\tB\x06\xe2\xde\x1f\x02ID\x12\x0e\n\x06height\x18\x02 \x01(\x03\x12!\n\x05\x62lame\x18\x03 \x01(\x0b\x32\x0c.types.BlameB\x04\xc8\xde\x1f\x00\x12\x0c\n\x04memo\x18\x04 \x01(\t\x12O\n\x05\x63oins\x18\x05 \x03(\x0b\x32\x0c.common.CoinB2\xaa\xdf\x1f*gitlab.com/thorchain/thornode/common.Coins\xc8\xde\x1f\x00\x12@\n\x07pub_key\x18\x06 \x01(\tB/\xfa\xde\x1f+gitlab.com/thorchain/thornode/common.PubKey\x12\x41\n\x06signer\x18\x07 \x01(\x0c\x42\x31\xfa\xde\x1f-github.com/cosmos/cosmos-sdk/types.AccAddressB5Z/gitlab.com/thorchain/thornode/x/thorchain/types\xc8\xe1\x1e\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'thorchain.v1.x.thorchain.types.msg_tss_keysign_fail_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z/gitlab.com/thorchain/thornode/x/thorchain/types\310\341\036\000'
  _MSGTSSKEYSIGNFAIL.fields_by_name['id']._options = None
  _MSGTSSKEYSIGNFAIL.fields_by_name['id']._serialized_options = b'\342\336\037\002ID'
  _MSGTSSKEYSIGNFAIL.fields_by_name['blame']._options = None
  _MSGTSSKEYSIGNFAIL.fields_by_name['blame']._serialized_options = b'\310\336\037\000'
  _MSGTSSKEYSIGNFAIL.fields_by_name['coins']._options = None
  _MSGTSSKEYSIGNFAIL.fields_by_name['coins']._serialized_options = b'\252\337\037*gitlab.com/thorchain/thornode/common.Coins\310\336\037\000'
  _MSGTSSKEYSIGNFAIL.fields_by_name['pub_key']._options = None
  _MSGTSSKEYSIGNFAIL.fields_by_name['pub_key']._serialized_options = b'\372\336\037+gitlab.com/thorchain/thornode/common.PubKey'
  _MSGTSSKEYSIGNFAIL.fields_by_name['signer']._options = None
  _MSGTSSKEYSIGNFAIL.fields_by_name['signer']._serialized_options = b'\372\336\037-github.com/cosmos/cosmos-sdk/types.AccAddress'
  _MSGTSSKEYSIGNFAIL._serialized_start=174
  _MSGTSSKEYSIGNFAIL._serialized_end=492
# @@protoc_insertion_point(module_scope)
