# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: thorchain/v1/x/thorchain/types/msg_bond.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from thorchain.v1.common import common_pb2 as thorchain_dot_v1_dot_common_dot_common__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-thorchain/v1/x/thorchain/types/msg_bond.proto\x12\x05types\x1a thorchain/v1/common/common.proto\x1a\x14gogoproto/gogo.proto\"\xa5\x03\n\x07MsgBond\x12\x1f\n\x05tx_in\x18\x01 \x01(\x0b\x32\n.common.TxB\x04\xc8\xde\x1f\x00\x12G\n\x0cnode_address\x18\x02 \x01(\x0c\x42\x31\xfa\xde\x1f-github.com/cosmos/cosmos-sdk/types.AccAddress\x12=\n\x04\x62ond\x18\x03 \x01(\tB/\xda\xde\x1f\'github.com/cosmos/cosmos-sdk/types.Uint\xc8\xde\x1f\x00\x12\x46\n\x0c\x62ond_address\x18\x04 \x01(\tB0\xfa\xde\x1f,gitlab.com/thorchain/thornode/common.Address\x12\x41\n\x06signer\x18\x05 \x01(\x0c\x42\x31\xfa\xde\x1f-github.com/cosmos/cosmos-sdk/types.AccAddress\x12P\n\x15\x62ond_provider_address\x18\x06 \x01(\x0c\x42\x31\xfa\xde\x1f-github.com/cosmos/cosmos-sdk/types.AccAddress\x12\x14\n\x0coperator_fee\x18\x07 \x01(\x03\x42\x31Z/gitlab.com/thorchain/thornode/x/thorchain/typesb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'thorchain.v1.x.thorchain.types.msg_bond_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z/gitlab.com/thorchain/thornode/x/thorchain/types'
  _MSGBOND.fields_by_name['tx_in']._options = None
  _MSGBOND.fields_by_name['tx_in']._serialized_options = b'\310\336\037\000'
  _MSGBOND.fields_by_name['node_address']._options = None
  _MSGBOND.fields_by_name['node_address']._serialized_options = b'\372\336\037-github.com/cosmos/cosmos-sdk/types.AccAddress'
  _MSGBOND.fields_by_name['bond']._options = None
  _MSGBOND.fields_by_name['bond']._serialized_options = b'\332\336\037\'github.com/cosmos/cosmos-sdk/types.Uint\310\336\037\000'
  _MSGBOND.fields_by_name['bond_address']._options = None
  _MSGBOND.fields_by_name['bond_address']._serialized_options = b'\372\336\037,gitlab.com/thorchain/thornode/common.Address'
  _MSGBOND.fields_by_name['signer']._options = None
  _MSGBOND.fields_by_name['signer']._serialized_options = b'\372\336\037-github.com/cosmos/cosmos-sdk/types.AccAddress'
  _MSGBOND.fields_by_name['bond_provider_address']._options = None
  _MSGBOND.fields_by_name['bond_provider_address']._serialized_options = b'\372\336\037-github.com/cosmos/cosmos-sdk/types.AccAddress'
  _MSGBOND._serialized_start=113
  _MSGBOND._serialized_end=534
# @@protoc_insertion_point(module_scope)
