"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class MsgNetworkFee(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BLOCK_HEIGHT_FIELD_NUMBER: builtins.int
    CHAIN_FIELD_NUMBER: builtins.int
    TRANSACTION_SIZE_FIELD_NUMBER: builtins.int
    TRANSACTION_FEE_RATE_FIELD_NUMBER: builtins.int
    SIGNER_FIELD_NUMBER: builtins.int
    block_height: builtins.int
    chain: builtins.str
    transaction_size: builtins.int
    transaction_fee_rate: builtins.int
    signer: builtins.bytes
    def __init__(
        self,
        *,
        block_height: builtins.int = ...,
        chain: builtins.str = ...,
        transaction_size: builtins.int = ...,
        transaction_fee_rate: builtins.int = ...,
        signer: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["block_height", b"block_height", "chain", b"chain", "signer", b"signer", "transaction_fee_rate", b"transaction_fee_rate", "transaction_size", b"transaction_size"]) -> None: ...

global___MsgNetworkFee = MsgNetworkFee
