# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: thorchain/v1/x/thorchain/types/msg_tss_pool.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from thorchain.v1.x.thorchain.types import type_blame_pb2 as thorchain_dot_v1_dot_x_dot_thorchain_dot_types_dot_type__blame__pb2
from thorchain.v1.x.thorchain.types import type_keygen_pb2 as thorchain_dot_v1_dot_x_dot_thorchain_dot_types_dot_type__keygen__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1thorchain/v1/x/thorchain/types/msg_tss_pool.proto\x12\x05types\x1a/thorchain/v1/x/thorchain/types/type_blame.proto\x1a\x30thorchain/v1/x/thorchain/types/type_keygen.proto\x1a\x14gogoproto/gogo.proto\"\xe6\x02\n\nMsgTssPool\x12\x12\n\x02id\x18\x01 \x01(\tB\x06\xe2\xde\x1f\x02ID\x12\x45\n\x0cpool_pub_key\x18\x02 \x01(\tB/\xfa\xde\x1f+gitlab.com/thorchain/thornode/common.PubKey\x12\x36\n\x0bkeygen_type\x18\x03 \x01(\x0e\x32\x11.types.KeygenTypeB\x0e\xfa\xde\x1f\nKeygenType\x12\x10\n\x08pub_keys\x18\x04 \x03(\t\x12\x0e\n\x06height\x18\x05 \x01(\x03\x12!\n\x05\x62lame\x18\x06 \x01(\x0b\x32\x0c.types.BlameB\x04\xc8\xde\x1f\x00\x12\x0e\n\x06\x63hains\x18\x07 \x03(\t\x12\x41\n\x06signer\x18\x08 \x01(\x0c\x42\x31\xfa\xde\x1f-github.com/cosmos/cosmos-sdk/types.AccAddress\x12\x13\n\x0bkeygen_time\x18\t \x01(\x03\x12\x18\n\x10keyshares_backup\x18\n \x01(\x0c\x42\x35Z/gitlab.com/thorchain/thornode/x/thorchain/types\xc8\xe1\x1e\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'thorchain.v1.x.thorchain.types.msg_tss_pool_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z/gitlab.com/thorchain/thornode/x/thorchain/types\310\341\036\000'
  _MSGTSSPOOL.fields_by_name['id']._options = None
  _MSGTSSPOOL.fields_by_name['id']._serialized_options = b'\342\336\037\002ID'
  _MSGTSSPOOL.fields_by_name['pool_pub_key']._options = None
  _MSGTSSPOOL.fields_by_name['pool_pub_key']._serialized_options = b'\372\336\037+gitlab.com/thorchain/thornode/common.PubKey'
  _MSGTSSPOOL.fields_by_name['keygen_type']._options = None
  _MSGTSSPOOL.fields_by_name['keygen_type']._serialized_options = b'\372\336\037\nKeygenType'
  _MSGTSSPOOL.fields_by_name['blame']._options = None
  _MSGTSSPOOL.fields_by_name['blame']._serialized_options = b'\310\336\037\000'
  _MSGTSSPOOL.fields_by_name['signer']._options = None
  _MSGTSSPOOL.fields_by_name['signer']._serialized_options = b'\372\336\037-github.com/cosmos/cosmos-sdk/types.AccAddress'
  _MSGTSSPOOL._serialized_start=182
  _MSGTSSPOOL._serialized_end=540
# @@protoc_insertion_point(module_scope)
