"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys
import thorchain.v1.common.common_pb2

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class Loan(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OWNER_FIELD_NUMBER: builtins.int
    ASSET_FIELD_NUMBER: builtins.int
    DEBT_UP_FIELD_NUMBER: builtins.int
    DEBT_DOWN_FIELD_NUMBER: builtins.int
    COLLATERAL_UP_FIELD_NUMBER: builtins.int
    COLLATERAL_DOWN_FIELD_NUMBER: builtins.int
    LAST_OPEN_HEIGHT_FIELD_NUMBER: builtins.int
    LAST_REPAY_HEIGHT_FIELD_NUMBER: builtins.int
    owner: builtins.str
    @property
    def asset(self) -> thorchain.v1.common.common_pb2.Asset: ...
    debt_up: builtins.str
    debt_down: builtins.str
    collateral_up: builtins.str
    collateral_down: builtins.str
    last_open_height: builtins.int
    last_repay_height: builtins.int
    def __init__(
        self,
        *,
        owner: builtins.str = ...,
        asset: thorchain.v1.common.common_pb2.Asset | None = ...,
        debt_up: builtins.str = ...,
        debt_down: builtins.str = ...,
        collateral_up: builtins.str = ...,
        collateral_down: builtins.str = ...,
        last_open_height: builtins.int = ...,
        last_repay_height: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["asset", b"asset"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["asset", b"asset", "collateral_down", b"collateral_down", "collateral_up", b"collateral_up", "debt_down", b"debt_down", "debt_up", b"debt_up", "last_open_height", b"last_open_height", "last_repay_height", b"last_repay_height", "owner", b"owner"]) -> None: ...

global___Loan = Loan
