"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class NodeTssTime(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ADDRESS_FIELD_NUMBER: builtins.int
    TSS_TIME_FIELD_NUMBER: builtins.int
    address: builtins.bytes
    tss_time: builtins.int
    def __init__(
        self,
        *,
        address: builtins.bytes = ...,
        tss_time: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["address", b"address", "tss_time", b"tss_time"]) -> None: ...

global___NodeTssTime = NodeTssTime

@typing_extensions.final
class TssKeygenMetric(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PUB_KEY_FIELD_NUMBER: builtins.int
    NODE_TSS_TIMES_FIELD_NUMBER: builtins.int
    pub_key: builtins.str
    @property
    def node_tss_times(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___NodeTssTime]: ...
    def __init__(
        self,
        *,
        pub_key: builtins.str = ...,
        node_tss_times: collections.abc.Iterable[global___NodeTssTime] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["node_tss_times", b"node_tss_times", "pub_key", b"pub_key"]) -> None: ...

global___TssKeygenMetric = TssKeygenMetric

@typing_extensions.final
class TssKeysignMetric(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TX_ID_FIELD_NUMBER: builtins.int
    NODE_TSS_TIMES_FIELD_NUMBER: builtins.int
    tx_id: builtins.str
    @property
    def node_tss_times(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___NodeTssTime]: ...
    def __init__(
        self,
        *,
        tx_id: builtins.str = ...,
        node_tss_times: collections.abc.Iterable[global___NodeTssTime] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["node_tss_times", b"node_tss_times", "tx_id", b"tx_id"]) -> None: ...

global___TssKeysignMetric = TssKeysignMetric
