"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class TssVoter(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    POOL_PUB_KEY_FIELD_NUMBER: builtins.int
    PUB_KEYS_FIELD_NUMBER: builtins.int
    BLOCK_HEIGHT_FIELD_NUMBER: builtins.int
    CHAINS_FIELD_NUMBER: builtins.int
    SIGNERS_FIELD_NUMBER: builtins.int
    MAJORITY_CONSENSUS_BLOCK_HEIGHT_FIELD_NUMBER: builtins.int
    id: builtins.str
    pool_pub_key: builtins.str
    @property
    def pub_keys(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    block_height: builtins.int
    @property
    def chains(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def signers(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    majority_consensus_block_height: builtins.int
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        pool_pub_key: builtins.str = ...,
        pub_keys: collections.abc.Iterable[builtins.str] | None = ...,
        block_height: builtins.int = ...,
        chains: collections.abc.Iterable[builtins.str] | None = ...,
        signers: collections.abc.Iterable[builtins.str] | None = ...,
        majority_consensus_block_height: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["block_height", b"block_height", "chains", b"chains", "id", b"id", "majority_consensus_block_height", b"majority_consensus_block_height", "pool_pub_key", b"pool_pub_key", "pub_keys", b"pub_keys", "signers", b"signers"]) -> None: ...

global___TssVoter = TssVoter
