# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: thorchain/v1/x/thorchain/types/type_vault.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from thorchain.v1.common import common_pb2 as thorchain_dot_v1_dot_common_dot_common__pb2
from thorchain.v1.x.thorchain.types import type_chain_contract_pb2 as thorchain_dot_v1_dot_x_dot_thorchain_dot_types_dot_type__chain__contract__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/thorchain/v1/x/thorchain/types/type_vault.proto\x12\x05types\x1a thorchain/v1/common/common.proto\x1a\x38thorchain/v1/x/thorchain/types/type_chain_contract.proto\x1a\x14gogoproto/gogo.proto\"\xb2\x03\n\x05Vault\x12\x14\n\x0c\x62lock_height\x18\x01 \x01(\x03\x12@\n\x07pub_key\x18\x02 \x01(\tB/\xfa\xde\x1f+gitlab.com/thorchain/thornode/common.PubKey\x12O\n\x05\x63oins\x18\x03 \x03(\x0b\x32\x0c.common.CoinB2\xaa\xdf\x1f*gitlab.com/thorchain/thornode/common.Coins\xc8\xde\x1f\x00\x12\x1e\n\x04type\x18\x04 \x01(\x0e\x32\x10.types.VaultType\x12\"\n\x06status\x18\x05 \x01(\x0e\x32\x12.types.VaultStatus\x12\x14\n\x0cstatus_since\x18\x06 \x01(\x03\x12\x12\n\nmembership\x18\x07 \x03(\t\x12\x0e\n\x06\x63hains\x18\x08 \x03(\t\x12\x18\n\x10inbound_tx_count\x18\t \x01(\x03\x12\x19\n\x11outbound_tx_count\x18\n \x01(\x03\x12 \n\x18pending_tx_block_heights\x18\x0b \x03(\x03\x12+\n\x07routers\x18\x16 \x03(\x0b\x32\x14.types.ChainContractB\x04\xc8\xde\x1f\x00*B\n\tVaultType\x12\x10\n\x0cUnknownVault\x10\x00\x12\x0f\n\x0b\x41sgardVault\x10\x01\x12\x12\n\x0eYggdrasilVault\x10\x02*S\n\x0bVaultStatus\x12\x11\n\rInactiveVault\x10\x00\x12\x0f\n\x0b\x41\x63tiveVault\x10\x01\x12\x11\n\rRetiringVault\x10\x02\x12\r\n\tInitVault\x10\x03\x42\x35Z/gitlab.com/thorchain/thornode/x/thorchain/types\xc8\xe1\x1e\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'thorchain.v1.x.thorchain.types.type_vault_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z/gitlab.com/thorchain/thornode/x/thorchain/types\310\341\036\000'
  _VAULT.fields_by_name['pub_key']._options = None
  _VAULT.fields_by_name['pub_key']._serialized_options = b'\372\336\037+gitlab.com/thorchain/thornode/common.PubKey'
  _VAULT.fields_by_name['coins']._options = None
  _VAULT.fields_by_name['coins']._serialized_options = b'\252\337\037*gitlab.com/thorchain/thornode/common.Coins\310\336\037\000'
  _VAULT.fields_by_name['routers']._options = None
  _VAULT.fields_by_name['routers']._serialized_options = b'\310\336\037\000'
  _VAULTTYPE._serialized_start=609
  _VAULTTYPE._serialized_end=675
  _VAULTSTATUS._serialized_start=677
  _VAULTSTATUS._serialized_end=760
  _VAULT._serialized_start=173
  _VAULT._serialized_end=607
# @@protoc_insertion_point(module_scope)
