# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: thorchain/v1/x/thorchain/types/type_ragnarok.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from thorchain.v1.common import common_pb2 as thorchain_dot_v1_dot_common_dot_common__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2thorchain/v1/x/thorchain/types/type_ragnarok.proto\x12\x05types\x1a thorchain/v1/common/common.proto\x1a\x14gogoproto/gogo.proto\"M\n\x18RagnarokWithdrawPosition\x12\x0e\n\x06number\x18\x01 \x01(\x03\x12!\n\x04pool\x18\x02 \x01(\x0b\x32\r.common.AssetB\x04\xc8\xde\x1f\x00\x42\x31Z/gitlab.com/thorchain/thornode/x/thorchain/typesb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'thorchain.v1.x.thorchain.types.type_ragnarok_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z/gitlab.com/thorchain/thornode/x/thorchain/types'
  _RAGNAROKWITHDRAWPOSITION.fields_by_name['pool']._options = None
  _RAGNAROKWITHDRAWPOSITION.fields_by_name['pool']._serialized_options = b'\310\336\037\000'
  _RAGNAROKWITHDRAWPOSITION._serialized_start=117
  _RAGNAROKWITHDRAWPOSITION._serialized_end=194
# @@protoc_insertion_point(module_scope)
