"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys
import thorchain.v1.common.common_pb2

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class SolvencyVoter(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    CHAIN_FIELD_NUMBER: builtins.int
    PUB_KEY_FIELD_NUMBER: builtins.int
    COINS_FIELD_NUMBER: builtins.int
    HEIGHT_FIELD_NUMBER: builtins.int
    CONSENSUS_BLOCK_HEIGHT_FIELD_NUMBER: builtins.int
    SIGNERS_FIELD_NUMBER: builtins.int
    id: builtins.str
    chain: builtins.str
    pub_key: builtins.str
    @property
    def coins(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[thorchain.v1.common.common_pb2.Coin]: ...
    height: builtins.int
    consensus_block_height: builtins.int
    @property
    def signers(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        chain: builtins.str = ...,
        pub_key: builtins.str = ...,
        coins: collections.abc.Iterable[thorchain.v1.common.common_pb2.Coin] | None = ...,
        height: builtins.int = ...,
        consensus_block_height: builtins.int = ...,
        signers: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["chain", b"chain", "coins", b"coins", "consensus_block_height", b"consensus_block_height", "height", b"height", "id", b"id", "pub_key", b"pub_key", "signers", b"signers"]) -> None: ...

global___SolvencyVoter = SolvencyVoter
