# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: thorchain/v1/x/thorchain/types/type_tss_metric.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n4thorchain/v1/x/thorchain/types/type_tss_metric.proto\x12\x05types\x1a\x14gogoproto/gogo.proto\"c\n\x0bNodeTssTime\x12\x42\n\x07\x61\x64\x64ress\x18\x01 \x01(\x0c\x42\x31\xfa\xde\x1f-github.com/cosmos/cosmos-sdk/types.AccAddress\x12\x10\n\x08tss_time\x18\x02 \x01(\x03\"\x85\x01\n\x0fTssKeygenMetric\x12@\n\x07pub_key\x18\x01 \x01(\tB/\xfa\xde\x1f+gitlab.com/thorchain/thornode/common.PubKey\x12\x30\n\x0enode_tss_times\x18\x02 \x03(\x0b\x32\x12.types.NodeTssTimeB\x04\xc8\xde\x1f\x00\"\x8a\x01\n\x10TssKeysignMetric\x12\x44\n\x05tx_id\x18\x01 \x01(\tB5\xfa\xde\x1f)gitlab.com/thorchain/thornode/common.TxID\xe2\xde\x1f\x04TxID\x12\x30\n\x0enode_tss_times\x18\x02 \x03(\x0b\x32\x12.types.NodeTssTimeB\x04\xc8\xde\x1f\x00\x42\x31Z/gitlab.com/thorchain/thornode/x/thorchain/typesb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'thorchain.v1.x.thorchain.types.type_tss_metric_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z/gitlab.com/thorchain/thornode/x/thorchain/types'
  _NODETSSTIME.fields_by_name['address']._options = None
  _NODETSSTIME.fields_by_name['address']._serialized_options = b'\372\336\037-github.com/cosmos/cosmos-sdk/types.AccAddress'
  _TSSKEYGENMETRIC.fields_by_name['pub_key']._options = None
  _TSSKEYGENMETRIC.fields_by_name['pub_key']._serialized_options = b'\372\336\037+gitlab.com/thorchain/thornode/common.PubKey'
  _TSSKEYGENMETRIC.fields_by_name['node_tss_times']._options = None
  _TSSKEYGENMETRIC.fields_by_name['node_tss_times']._serialized_options = b'\310\336\037\000'
  _TSSKEYSIGNMETRIC.fields_by_name['tx_id']._options = None
  _TSSKEYSIGNMETRIC.fields_by_name['tx_id']._serialized_options = b'\372\336\037)gitlab.com/thorchain/thornode/common.TxID\342\336\037\004TxID'
  _TSSKEYSIGNMETRIC.fields_by_name['node_tss_times']._options = None
  _TSSKEYSIGNMETRIC.fields_by_name['node_tss_times']._serialized_options = b'\310\336\037\000'
  _NODETSSTIME._serialized_start=85
  _NODETSSTIME._serialized_end=184
  _TSSKEYGENMETRIC._serialized_start=187
  _TSSKEYGENMETRIC._serialized_end=320
  _TSSKEYSIGNMETRIC._serialized_start=323
  _TSSKEYSIGNMETRIC._serialized_end=461
# @@protoc_insertion_point(module_scope)
