# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: thorchain/v1/x/thorchain/types/type_mimir.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/thorchain/v1/x/thorchain/types/type_mimir.proto\x12\x05types\x1a\x14gogoproto/gogo.proto\"j\n\tNodeMimir\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x03\x12\x41\n\x06signer\x18\x03 \x01(\x0c\x42\x31\xfa\xde\x1f-github.com/cosmos/cosmos-sdk/types.AccAddress\"4\n\nNodeMimirs\x12&\n\x06mimirs\x18\x01 \x03(\x0b\x32\x10.types.NodeMimirB\x04\xc8\xde\x1f\x00\x42\x31Z/gitlab.com/thorchain/thornode/x/thorchain/typesb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'thorchain.v1.x.thorchain.types.type_mimir_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z/gitlab.com/thorchain/thornode/x/thorchain/types'
  _NODEMIMIR.fields_by_name['signer']._options = None
  _NODEMIMIR.fields_by_name['signer']._serialized_options = b'\372\336\037-github.com/cosmos/cosmos-sdk/types.AccAddress'
  _NODEMIMIRS.fields_by_name['mimirs']._options = None
  _NODEMIMIRS.fields_by_name['mimirs']._serialized_options = b'\310\336\037\000'
  _NODEMIMIR._serialized_start=80
  _NODEMIMIR._serialized_end=186
  _NODEMIMIRS._serialized_start=188
  _NODEMIMIRS._serialized_end=240
# @@protoc_insertion_point(module_scope)
