"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import thorchain.v1.common.common_pb2
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _PoolStatus:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _PoolStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_PoolStatus.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    UnknownPoolStatus: _PoolStatus.ValueType  # 0
    Available: _PoolStatus.ValueType  # 1
    Staged: _PoolStatus.ValueType  # 2
    Suspended: _PoolStatus.ValueType  # 3

class PoolStatus(_PoolStatus, metaclass=_PoolStatusEnumTypeWrapper):
    """|    State    | Swap | Add   | Withdraw  | Refunding |
    | ----------- | ---- | ----- | --------- | --------- |
    | `staged`    | no   | yes   | yes       | Refund Invalid Add/Remove Liquidity && all Swaps |
    | `available` | yes  | yes   | yes       | Refund Invalid Tx |
    | `suspended` | no   | no    | no        | Refund all |
    """

UnknownPoolStatus: PoolStatus.ValueType  # 0
Available: PoolStatus.ValueType  # 1
Staged: PoolStatus.ValueType  # 2
Suspended: PoolStatus.ValueType  # 3
global___PoolStatus = PoolStatus

@typing_extensions.final
class Pool(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BALANCE_RUNE_FIELD_NUMBER: builtins.int
    BALANCE_ASSET_FIELD_NUMBER: builtins.int
    ASSET_FIELD_NUMBER: builtins.int
    LP_UNITS_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    STATUS_SINCE_FIELD_NUMBER: builtins.int
    DECIMALS_FIELD_NUMBER: builtins.int
    SYNTH_UNITS_FIELD_NUMBER: builtins.int
    PENDING_INBOUND_RUNE_FIELD_NUMBER: builtins.int
    PENDING_INBOUND_ASSET_FIELD_NUMBER: builtins.int
    balance_rune: builtins.str
    balance_asset: builtins.str
    @property
    def asset(self) -> thorchain.v1.common.common_pb2.Asset: ...
    LP_units: builtins.str
    status: global___PoolStatus.ValueType
    status_since: builtins.int
    decimals: builtins.int
    synth_units: builtins.str
    pending_inbound_rune: builtins.str
    pending_inbound_asset: builtins.str
    def __init__(
        self,
        *,
        balance_rune: builtins.str = ...,
        balance_asset: builtins.str = ...,
        asset: thorchain.v1.common.common_pb2.Asset | None = ...,
        LP_units: builtins.str = ...,
        status: global___PoolStatus.ValueType = ...,
        status_since: builtins.int = ...,
        decimals: builtins.int = ...,
        synth_units: builtins.str = ...,
        pending_inbound_rune: builtins.str = ...,
        pending_inbound_asset: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["asset", b"asset"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["LP_units", b"LP_units", "asset", b"asset", "balance_asset", b"balance_asset", "balance_rune", b"balance_rune", "decimals", b"decimals", "pending_inbound_asset", b"pending_inbound_asset", "pending_inbound_rune", b"pending_inbound_rune", "status", b"status", "status_since", b"status_since", "synth_units", b"synth_units"]) -> None: ...

global___Pool = Pool
