"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys
import thorchain.v1.common.common_pb2

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class LiquidityProvider(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ASSET_FIELD_NUMBER: builtins.int
    RUNE_ADDRESS_FIELD_NUMBER: builtins.int
    ASSET_ADDRESS_FIELD_NUMBER: builtins.int
    LAST_ADD_HEIGHT_FIELD_NUMBER: builtins.int
    LAST_WITHDRAW_HEIGHT_FIELD_NUMBER: builtins.int
    UNITS_FIELD_NUMBER: builtins.int
    PENDING_RUNE_FIELD_NUMBER: builtins.int
    PENDING_ASSET_FIELD_NUMBER: builtins.int
    PENDING_TX_ID_FIELD_NUMBER: builtins.int
    RUNE_DEPOSIT_VALUE_FIELD_NUMBER: builtins.int
    ASSET_DEPOSIT_VALUE_FIELD_NUMBER: builtins.int
    @property
    def asset(self) -> thorchain.v1.common.common_pb2.Asset: ...
    rune_address: builtins.str
    asset_address: builtins.str
    last_add_height: builtins.int
    last_withdraw_height: builtins.int
    units: builtins.str
    pending_rune: builtins.str
    pending_asset: builtins.str
    pending_tx_Id: builtins.str
    rune_deposit_value: builtins.str
    asset_deposit_value: builtins.str
    def __init__(
        self,
        *,
        asset: thorchain.v1.common.common_pb2.Asset | None = ...,
        rune_address: builtins.str = ...,
        asset_address: builtins.str = ...,
        last_add_height: builtins.int = ...,
        last_withdraw_height: builtins.int = ...,
        units: builtins.str = ...,
        pending_rune: builtins.str = ...,
        pending_asset: builtins.str = ...,
        pending_tx_Id: builtins.str = ...,
        rune_deposit_value: builtins.str = ...,
        asset_deposit_value: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["asset", b"asset"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["asset", b"asset", "asset_address", b"asset_address", "asset_deposit_value", b"asset_deposit_value", "last_add_height", b"last_add_height", "last_withdraw_height", b"last_withdraw_height", "pending_asset", b"pending_asset", "pending_rune", b"pending_rune", "pending_tx_Id", b"pending_tx_Id", "rune_address", b"rune_address", "rune_deposit_value", b"rune_deposit_value", "units", b"units"]) -> None: ...

global___LiquidityProvider = LiquidityProvider
