"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys
import thorchain.v1.common.common_pb2

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class THORNameAlias(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CHAIN_FIELD_NUMBER: builtins.int
    ADDRESS_FIELD_NUMBER: builtins.int
    chain: builtins.str
    address: builtins.str
    def __init__(
        self,
        *,
        chain: builtins.str = ...,
        address: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["address", b"address", "chain", b"chain"]) -> None: ...

global___THORNameAlias = THORNameAlias

@typing_extensions.final
class THORName(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    EXPIRE_BLOCK_HEIGHT_FIELD_NUMBER: builtins.int
    OWNER_FIELD_NUMBER: builtins.int
    PREFERRED_ASSET_FIELD_NUMBER: builtins.int
    ALIASES_FIELD_NUMBER: builtins.int
    name: builtins.str
    expire_block_height: builtins.int
    owner: builtins.bytes
    @property
    def preferred_asset(self) -> thorchain.v1.common.common_pb2.Asset: ...
    @property
    def aliases(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___THORNameAlias]: ...
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        expire_block_height: builtins.int = ...,
        owner: builtins.bytes = ...,
        preferred_asset: thorchain.v1.common.common_pb2.Asset | None = ...,
        aliases: collections.abc.Iterable[global___THORNameAlias] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["preferred_asset", b"preferred_asset"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["aliases", b"aliases", "expire_block_height", b"expire_block_height", "name", b"name", "owner", b"owner", "preferred_asset", b"preferred_asset"]) -> None: ...

global___THORName = THORName
