# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: thorchain/v1/x/thorchain/types/type_loan.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from thorchain.v1.common import common_pb2 as thorchain_dot_v1_dot_common_dot_common__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.thorchain/v1/x/thorchain/types/type_loan.proto\x12\x05types\x1a thorchain/v1/common/common.proto\x1a\x14gogoproto/gogo.proto\"\xb8\x03\n\x04Loan\x12?\n\x05owner\x18\x01 \x01(\tB0\xfa\xde\x1f,gitlab.com/thorchain/thornode/common.Address\x12\"\n\x05\x61sset\x18\x02 \x01(\x0b\x32\r.common.AssetB\x04\xc8\xde\x1f\x00\x12@\n\x07\x64\x65\x62t_up\x18\x03 \x01(\tB/\xda\xde\x1f\'github.com/cosmos/cosmos-sdk/types.Uint\xc8\xde\x1f\x00\x12\x42\n\tdebt_down\x18\x04 \x01(\tB/\xda\xde\x1f\'github.com/cosmos/cosmos-sdk/types.Uint\xc8\xde\x1f\x00\x12\x46\n\rcollateral_up\x18\x05 \x01(\tB/\xda\xde\x1f\'github.com/cosmos/cosmos-sdk/types.Uint\xc8\xde\x1f\x00\x12H\n\x0f\x63ollateral_down\x18\x06 \x01(\tB/\xda\xde\x1f\'github.com/cosmos/cosmos-sdk/types.Uint\xc8\xde\x1f\x00\x12\x18\n\x10last_open_height\x18\t \x01(\x03\x12\x19\n\x11last_repay_height\x18\n \x01(\x03\x42\x31Z/gitlab.com/thorchain/thornode/x/thorchain/typesb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'thorchain.v1.x.thorchain.types.type_loan_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z/gitlab.com/thorchain/thornode/x/thorchain/types'
  _LOAN.fields_by_name['owner']._options = None
  _LOAN.fields_by_name['owner']._serialized_options = b'\372\336\037,gitlab.com/thorchain/thornode/common.Address'
  _LOAN.fields_by_name['asset']._options = None
  _LOAN.fields_by_name['asset']._serialized_options = b'\310\336\037\000'
  _LOAN.fields_by_name['debt_up']._options = None
  _LOAN.fields_by_name['debt_up']._serialized_options = b'\332\336\037\'github.com/cosmos/cosmos-sdk/types.Uint\310\336\037\000'
  _LOAN.fields_by_name['debt_down']._options = None
  _LOAN.fields_by_name['debt_down']._serialized_options = b'\332\336\037\'github.com/cosmos/cosmos-sdk/types.Uint\310\336\037\000'
  _LOAN.fields_by_name['collateral_up']._options = None
  _LOAN.fields_by_name['collateral_up']._serialized_options = b'\332\336\037\'github.com/cosmos/cosmos-sdk/types.Uint\310\336\037\000'
  _LOAN.fields_by_name['collateral_down']._options = None
  _LOAN.fields_by_name['collateral_down']._serialized_options = b'\332\336\037\'github.com/cosmos/cosmos-sdk/types.Uint\310\336\037\000'
  _LOAN._serialized_start=114
  _LOAN._serialized_end=554
# @@protoc_insertion_point(module_scope)
