"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class ObservedNetworkFeeVoter(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BLOCK_HEIGHT_FIELD_NUMBER: builtins.int
    REPORT_BLOCK_HEIGHT_FIELD_NUMBER: builtins.int
    CHAIN_FIELD_NUMBER: builtins.int
    SIGNERS_FIELD_NUMBER: builtins.int
    FEE_RATE_FIELD_NUMBER: builtins.int
    block_height: builtins.int
    report_block_height: builtins.int
    chain: builtins.str
    @property
    def signers(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    fee_rate: builtins.int
    def __init__(
        self,
        *,
        block_height: builtins.int = ...,
        report_block_height: builtins.int = ...,
        chain: builtins.str = ...,
        signers: collections.abc.Iterable[builtins.str] | None = ...,
        fee_rate: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["block_height", b"block_height", "chain", b"chain", "fee_rate", b"fee_rate", "report_block_height", b"report_block_height", "signers", b"signers"]) -> None: ...

global___ObservedNetworkFeeVoter = ObservedNetworkFeeVoter
