# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: thorchain/v1/x/thorchain/types/type_keygen.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0thorchain/v1/x/thorchain/types/type_keygen.proto\x12\x05types\x1a\x14gogoproto/gogo.proto\"{\n\x06Keygen\x12?\n\x02id\x18\x01 \x01(\tB3\xfa\xde\x1f)gitlab.com/thorchain/thornode/common.TxID\xe2\xde\x1f\x02ID\x12\x1f\n\x04type\x18\x02 \x01(\x0e\x32\x11.types.KeygenType\x12\x0f\n\x07members\x18\x03 \x03(\t\"C\n\x0bKeygenBlock\x12\x0e\n\x06height\x18\x01 \x01(\x03\x12$\n\x07keygens\x18\x04 \x03(\x0b\x32\r.types.KeygenB\x04\xc8\xde\x1f\x00*F\n\nKeygenType\x12\x11\n\rUnknownKeygen\x10\x00\x12\x10\n\x0c\x41sgardKeygen\x10\x01\x12\x13\n\x0fYggdrasilKeygen\x10\x02\x42=Z/gitlab.com/thorchain/thornode/x/thorchain/types\xd8\xe1\x1e\x00\x80\xe2\x1e\x00\xc8\xe1\x1e\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'thorchain.v1.x.thorchain.types.type_keygen_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z/gitlab.com/thorchain/thornode/x/thorchain/types\330\341\036\000\200\342\036\000\310\341\036\000'
  _KEYGEN.fields_by_name['id']._options = None
  _KEYGEN.fields_by_name['id']._serialized_options = b'\372\336\037)gitlab.com/thorchain/thornode/common.TxID\342\336\037\002ID'
  _KEYGENBLOCK.fields_by_name['keygens']._options = None
  _KEYGENBLOCK.fields_by_name['keygens']._serialized_options = b'\310\336\037\000'
  _KEYGENTYPE._serialized_start=275
  _KEYGENTYPE._serialized_end=345
  _KEYGEN._serialized_start=81
  _KEYGEN._serialized_end=204
  _KEYGENBLOCK._serialized_start=206
  _KEYGENBLOCK._serialized_end=273
# @@protoc_insertion_point(module_scope)
