# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: thorchain/v1/x/thorchain/types/type_pool.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from thorchain.v1.common import common_pb2 as thorchain_dot_v1_dot_common_dot_common__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.thorchain/v1/x/thorchain/types/type_pool.proto\x12\x05types\x1a thorchain/v1/common/common.proto\x1a\x14gogoproto/gogo.proto\"\xac\x04\n\x04Pool\x12\x45\n\x0c\x62\x61lance_rune\x18\x01 \x01(\tB/\xda\xde\x1f\'github.com/cosmos/cosmos-sdk/types.Uint\xc8\xde\x1f\x00\x12\x46\n\rbalance_asset\x18\x02 \x01(\tB/\xda\xde\x1f\'github.com/cosmos/cosmos-sdk/types.Uint\xc8\xde\x1f\x00\x12\"\n\x05\x61sset\x18\x03 \x01(\x0b\x32\r.common.AssetB\x04\xc8\xde\x1f\x00\x12\x41\n\x08LP_units\x18\x04 \x01(\tB/\xda\xde\x1f\'github.com/cosmos/cosmos-sdk/types.Uint\xc8\xde\x1f\x00\x12!\n\x06status\x18\x05 \x01(\x0e\x32\x11.types.PoolStatus\x12\x14\n\x0cstatus_since\x18\n \x01(\x03\x12\x10\n\x08\x64\x65\x63imals\x18\x06 \x01(\x03\x12\x44\n\x0bsynth_units\x18\x07 \x01(\tB/\xda\xde\x1f\'github.com/cosmos/cosmos-sdk/types.Uint\xc8\xde\x1f\x00\x12M\n\x14pending_inbound_rune\x18\x08 \x01(\tB/\xda\xde\x1f\'github.com/cosmos/cosmos-sdk/types.Uint\xc8\xde\x1f\x00\x12N\n\x15pending_inbound_asset\x18\t \x01(\tB/\xda\xde\x1f\'github.com/cosmos/cosmos-sdk/types.Uint\xc8\xde\x1f\x00*M\n\nPoolStatus\x12\x15\n\x11UnknownPoolStatus\x10\x00\x12\r\n\tAvailable\x10\x01\x12\n\n\x06Staged\x10\x02\x12\r\n\tSuspended\x10\x03\x42=Z/gitlab.com/thorchain/thornode/x/thorchain/types\xd8\xe1\x1e\x00\x80\xe2\x1e\x00\xc8\xe1\x1e\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'thorchain.v1.x.thorchain.types.type_pool_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z/gitlab.com/thorchain/thornode/x/thorchain/types\330\341\036\000\200\342\036\000\310\341\036\000'
  _POOL.fields_by_name['balance_rune']._options = None
  _POOL.fields_by_name['balance_rune']._serialized_options = b'\332\336\037\'github.com/cosmos/cosmos-sdk/types.Uint\310\336\037\000'
  _POOL.fields_by_name['balance_asset']._options = None
  _POOL.fields_by_name['balance_asset']._serialized_options = b'\332\336\037\'github.com/cosmos/cosmos-sdk/types.Uint\310\336\037\000'
  _POOL.fields_by_name['asset']._options = None
  _POOL.fields_by_name['asset']._serialized_options = b'\310\336\037\000'
  _POOL.fields_by_name['LP_units']._options = None
  _POOL.fields_by_name['LP_units']._serialized_options = b'\332\336\037\'github.com/cosmos/cosmos-sdk/types.Uint\310\336\037\000'
  _POOL.fields_by_name['synth_units']._options = None
  _POOL.fields_by_name['synth_units']._serialized_options = b'\332\336\037\'github.com/cosmos/cosmos-sdk/types.Uint\310\336\037\000'
  _POOL.fields_by_name['pending_inbound_rune']._options = None
  _POOL.fields_by_name['pending_inbound_rune']._serialized_options = b'\332\336\037\'github.com/cosmos/cosmos-sdk/types.Uint\310\336\037\000'
  _POOL.fields_by_name['pending_inbound_asset']._options = None
  _POOL.fields_by_name['pending_inbound_asset']._serialized_options = b'\332\336\037\'github.com/cosmos/cosmos-sdk/types.Uint\310\336\037\000'
  _POOLSTATUS._serialized_start=672
  _POOLSTATUS._serialized_end=749
  _POOL._serialized_start=114
  _POOL._serialized_end=670
# @@protoc_insertion_point(module_scope)
