# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: thorchain/v1/x/thorchain/types/type_reserve_contributor.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n=thorchain/v1/x/thorchain/types/type_reserve_contributor.proto\x12\x05types\x1a\x14gogoproto/gogo.proto\"\x98\x01\n\x12ReserveContributor\x12\x41\n\x07\x61\x64\x64ress\x18\x01 \x01(\tB0\xfa\xde\x1f,gitlab.com/thorchain/thornode/common.Address\x12?\n\x06\x61mount\x18\x02 \x01(\tB/\xda\xde\x1f\'github.com/cosmos/cosmos-sdk/types.Uint\xc8\xde\x1f\x00\x42\x31Z/gitlab.com/thorchain/thornode/x/thorchain/typesb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'thorchain.v1.x.thorchain.types.type_reserve_contributor_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z/gitlab.com/thorchain/thornode/x/thorchain/types'
  _RESERVECONTRIBUTOR.fields_by_name['address']._options = None
  _RESERVECONTRIBUTOR.fields_by_name['address']._serialized_options = b'\372\336\037,gitlab.com/thorchain/thornode/common.Address'
  _RESERVECONTRIBUTOR.fields_by_name['amount']._options = None
  _RESERVECONTRIBUTOR.fields_by_name['amount']._serialized_options = b'\332\336\037\'github.com/cosmos/cosmos-sdk/types.Uint\310\336\037\000'
  _RESERVECONTRIBUTOR._serialized_start=95
  _RESERVECONTRIBUTOR._serialized_end=247
# @@protoc_insertion_point(module_scope)
