"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class Node(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PUBKEY_FIELD_NUMBER: builtins.int
    BLAME_DATA_FIELD_NUMBER: builtins.int
    BLAME_SIGNATURE_FIELD_NUMBER: builtins.int
    pubkey: builtins.str
    blame_data: builtins.bytes
    blame_signature: builtins.bytes
    def __init__(
        self,
        *,
        pubkey: builtins.str = ...,
        blame_data: builtins.bytes = ...,
        blame_signature: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["blame_data", b"blame_data", "blame_signature", b"blame_signature", "pubkey", b"pubkey"]) -> None: ...

global___Node = Node

@typing_extensions.final
class Blame(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FAIL_REASON_FIELD_NUMBER: builtins.int
    IS_UNICAST_FIELD_NUMBER: builtins.int
    BLAME_NODES_FIELD_NUMBER: builtins.int
    fail_reason: builtins.str
    is_unicast: builtins.bool
    @property
    def blame_nodes(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Node]: ...
    def __init__(
        self,
        *,
        fail_reason: builtins.str = ...,
        is_unicast: builtins.bool = ...,
        blame_nodes: collections.abc.Iterable[global___Node] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["blame_nodes", b"blame_nodes", "fail_reason", b"fail_reason", "is_unicast", b"is_unicast"]) -> None: ...

global___Blame = Blame
