# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: thorchain/v1/x/thorchain/types/type_thorname.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from thorchain.v1.common import common_pb2 as thorchain_dot_v1_dot_common_dot_common__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2thorchain/v1/x/thorchain/types/type_thorname.proto\x12\x05types\x1a thorchain/v1/common/common.proto\x1a\x14gogoproto/gogo.proto\"\x91\x01\n\rTHORNameAlias\x12=\n\x05\x63hain\x18\x01 \x01(\tB.\xfa\xde\x1f*gitlab.com/thorchain/thornode/common.Chain\x12\x41\n\x07\x61\x64\x64ress\x18\x02 \x01(\tB0\xfa\xde\x1f,gitlab.com/thorchain/thornode/common.Address\"\xd2\x01\n\x08THORName\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x1b\n\x13\x65xpire_block_height\x18\x02 \x01(\x03\x12@\n\x05owner\x18\x03 \x01(\x0c\x42\x31\xfa\xde\x1f-github.com/cosmos/cosmos-sdk/types.AccAddress\x12,\n\x0fpreferred_asset\x18\x04 \x01(\x0b\x32\r.common.AssetB\x04\xc8\xde\x1f\x00\x12+\n\x07\x61liases\x18\x05 \x03(\x0b\x32\x14.types.THORNameAliasB\x04\xc8\xde\x1f\x00\x42\x31Z/gitlab.com/thorchain/thornode/x/thorchain/typesb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'thorchain.v1.x.thorchain.types.type_thorname_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z/gitlab.com/thorchain/thornode/x/thorchain/types'
  _THORNAMEALIAS.fields_by_name['chain']._options = None
  _THORNAMEALIAS.fields_by_name['chain']._serialized_options = b'\372\336\037*gitlab.com/thorchain/thornode/common.Chain'
  _THORNAMEALIAS.fields_by_name['address']._options = None
  _THORNAMEALIAS.fields_by_name['address']._serialized_options = b'\372\336\037,gitlab.com/thorchain/thornode/common.Address'
  _THORNAME.fields_by_name['owner']._options = None
  _THORNAME.fields_by_name['owner']._serialized_options = b'\372\336\037-github.com/cosmos/cosmos-sdk/types.AccAddress'
  _THORNAME.fields_by_name['preferred_asset']._options = None
  _THORNAME.fields_by_name['preferred_asset']._serialized_options = b'\310\336\037\000'
  _THORNAME.fields_by_name['aliases']._options = None
  _THORNAME.fields_by_name['aliases']._serialized_options = b'\310\336\037\000'
  _THORNAMEALIAS._serialized_start=118
  _THORNAMEALIAS._serialized_end=263
  _THORNAME._serialized_start=266
  _THORNAME._serialized_end=476
# @@protoc_insertion_point(module_scope)
