# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: thorchain/v1/x/thorchain/types/type_blame.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/thorchain/v1/x/thorchain/types/type_blame.proto\x12\x05types\x1a\x14gogoproto/gogo.proto\"C\n\x04Node\x12\x0e\n\x06pubkey\x18\x01 \x01(\t\x12\x12\n\nblame_data\x18\x02 \x01(\x0c\x12\x17\n\x0f\x62lame_signature\x18\x03 \x01(\x0c\"X\n\x05\x42lame\x12\x13\n\x0b\x66\x61il_reason\x18\x01 \x01(\t\x12\x12\n\nis_unicast\x18\x02 \x01(\x08\x12&\n\x0b\x62lame_nodes\x18\x03 \x03(\x0b\x32\x0b.types.NodeB\x04\xc8\xde\x1f\x00\x42=Z/gitlab.com/thorchain/thornode/x/thorchain/types\xd8\xe1\x1e\x00\x80\xe2\x1e\x00\xc8\xe1\x1e\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'thorchain.v1.x.thorchain.types.type_blame_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z/gitlab.com/thorchain/thornode/x/thorchain/types\330\341\036\000\200\342\036\000\310\341\036\000'
  _BLAME.fields_by_name['blame_nodes']._options = None
  _BLAME.fields_by_name['blame_nodes']._serialized_options = b'\310\336\037\000'
  _NODE._serialized_start=80
  _NODE._serialized_end=147
  _BLAME._serialized_start=149
  _BLAME._serialized_end=237
# @@protoc_insertion_point(module_scope)
