"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys
import thorchain.v1.common.common_pb2

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class RagnarokWithdrawPosition(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NUMBER_FIELD_NUMBER: builtins.int
    POOL_FIELD_NUMBER: builtins.int
    number: builtins.int
    @property
    def pool(self) -> thorchain.v1.common.common_pb2.Asset: ...
    def __init__(
        self,
        *,
        number: builtins.int = ...,
        pool: thorchain.v1.common.common_pb2.Asset | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["pool", b"pool"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["number", b"number", "pool", b"pool"]) -> None: ...

global___RagnarokWithdrawPosition = RagnarokWithdrawPosition
