# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: thorchain/v1/x/thorchain/types/type_solvency_voter.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from thorchain.v1.common import common_pb2 as thorchain_dot_v1_dot_common_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n8thorchain/v1/x/thorchain/types/type_solvency_voter.proto\x12\x05types\x1a\x14gogoproto/gogo.proto\x1a thorchain/v1/common/common.proto\"\xdd\x02\n\rSolvencyVoter\x12\x39\n\x02id\x18\x01 \x01(\tB-\xfa\xde\x1f)gitlab.com/thorchain/thornode/common.TxID\x12=\n\x05\x63hain\x18\x02 \x01(\tB.\xfa\xde\x1f*gitlab.com/thorchain/thornode/common.Chain\x12@\n\x07pub_key\x18\x03 \x01(\tB/\xfa\xde\x1f+gitlab.com/thorchain/thornode/common.PubKey\x12O\n\x05\x63oins\x18\x04 \x03(\x0b\x32\x0c.common.CoinB2\xaa\xdf\x1f*gitlab.com/thorchain/thornode/common.Coins\xc8\xde\x1f\x00\x12\x0e\n\x06height\x18\x05 \x01(\x03\x12\x1e\n\x16\x63onsensus_block_height\x18\x06 \x01(\x03\x12\x0f\n\x07signers\x18\x07 \x03(\tB=Z/gitlab.com/thorchain/thornode/x/thorchain/types\xd8\xe1\x1e\x00\x80\xe2\x1e\x00\xc8\xe1\x1e\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'thorchain.v1.x.thorchain.types.type_solvency_voter_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z/gitlab.com/thorchain/thornode/x/thorchain/types\330\341\036\000\200\342\036\000\310\341\036\000'
  _SOLVENCYVOTER.fields_by_name['id']._options = None
  _SOLVENCYVOTER.fields_by_name['id']._serialized_options = b'\372\336\037)gitlab.com/thorchain/thornode/common.TxID'
  _SOLVENCYVOTER.fields_by_name['chain']._options = None
  _SOLVENCYVOTER.fields_by_name['chain']._serialized_options = b'\372\336\037*gitlab.com/thorchain/thornode/common.Chain'
  _SOLVENCYVOTER.fields_by_name['pub_key']._options = None
  _SOLVENCYVOTER.fields_by_name['pub_key']._serialized_options = b'\372\336\037+gitlab.com/thorchain/thornode/common.PubKey'
  _SOLVENCYVOTER.fields_by_name['coins']._options = None
  _SOLVENCYVOTER.fields_by_name['coins']._serialized_options = b'\252\337\037*gitlab.com/thorchain/thornode/common.Coins\310\336\037\000'
  _SOLVENCYVOTER._serialized_start=124
  _SOLVENCYVOTER._serialized_end=473
# @@protoc_insertion_point(module_scope)
