# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: thorchain/v1/x/thorchain/types/type_observed_tx.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from thorchain.v1.common import common_pb2 as thorchain_dot_v1_dot_common_dot_common__pb2
from thorchain.v1.x.thorchain.types import type_tx_out_pb2 as thorchain_dot_v1_dot_x_dot_thorchain_dot_types_dot_type__tx__out__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5thorchain/v1/x/thorchain/types/type_observed_tx.proto\x12\x05types\x1a thorchain/v1/common/common.proto\x1a\x30thorchain/v1/x/thorchain/types/type_tx_out.proto\x1a\x14gogoproto/gogo.proto\"\xfd\x02\n\nObservedTx\x12\x1c\n\x02tx\x18\x01 \x01(\x0b\x32\n.common.TxB\x04\xc8\xde\x1f\x00\x12\x1d\n\x06status\x18\x02 \x01(\x0e\x32\r.types.Status\x12\x12\n\nout_hashes\x18\x03 \x03(\t\x12\x14\n\x0c\x62lock_height\x18\x04 \x01(\x03\x12\x0f\n\x07signers\x18\x05 \x03(\t\x12I\n\x10observed_pub_key\x18\x06 \x01(\tB/\xfa\xde\x1f+gitlab.com/thorchain/thornode/common.PubKey\x12\x12\n\nkeysign_ms\x18\x07 \x01(\x03\x12\x17\n\x0f\x66inalise_height\x18\x08 \x01(\x03\x12\x12\n\naggregator\x18\t \x01(\t\x12\x19\n\x11\x61ggregator_target\x18\n \x01(\t\x12P\n\x17\x61ggregator_target_limit\x18\x0b \x01(\tB/\xda\xde\x1f\'github.com/cosmos/cosmos-sdk/types.Uint\xc8\xde\x1f\x01\"\x95\x03\n\x0fObservedTxVoter\x12\x44\n\x05tx_id\x18\x01 \x01(\tB5\xfa\xde\x1f)gitlab.com/thorchain/thornode/common.TxID\xe2\xde\x1f\x04TxID\x12#\n\x02tx\x18\x02 \x01(\x0b\x32\x11.types.ObservedTxB\x04\xc8\xde\x1f\x00\x12\x0e\n\x06height\x18\x03 \x01(\x03\x12\x33\n\x03txs\x18\x04 \x03(\x0b\x32\x11.types.ObservedTxB\x13\xaa\xdf\x1f\x0bObservedTxs\xc8\xde\x1f\x00\x12\'\n\x07\x61\x63tions\x18\x05 \x03(\x0b\x32\x10.types.TxOutItemB\x04\xc8\xde\x1f\x00\x12M\n\x07out_txs\x18\x06 \x03(\x0b\x32\n.common.TxB0\xaa\xdf\x1f(gitlab.com/thorchain/thornode/common.Txs\xc8\xde\x1f\x00\x12\x18\n\x10\x66inalised_height\x18\x07 \x01(\x03\x12\x15\n\rupdated_vault\x18\x08 \x01(\x08\x12\x10\n\x08reverted\x18\t \x01(\x08\x12\x17\n\x0foutbound_height\x18\n \x01(\x03*0\n\x06Status\x12\x0e\n\nincomplete\x10\x00\x12\x08\n\x04\x64one\x10\x01\x12\x0c\n\x08reverted\x10\x02\x42=Z/gitlab.com/thorchain/thornode/x/thorchain/types\xd8\xe1\x1e\x00\x80\xe2\x1e\x00\xc8\xe1\x1e\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'thorchain.v1.x.thorchain.types.type_observed_tx_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z/gitlab.com/thorchain/thornode/x/thorchain/types\330\341\036\000\200\342\036\000\310\341\036\000'
  _OBSERVEDTX.fields_by_name['tx']._options = None
  _OBSERVEDTX.fields_by_name['tx']._serialized_options = b'\310\336\037\000'
  _OBSERVEDTX.fields_by_name['observed_pub_key']._options = None
  _OBSERVEDTX.fields_by_name['observed_pub_key']._serialized_options = b'\372\336\037+gitlab.com/thorchain/thornode/common.PubKey'
  _OBSERVEDTX.fields_by_name['aggregator_target_limit']._options = None
  _OBSERVEDTX.fields_by_name['aggregator_target_limit']._serialized_options = b'\332\336\037\'github.com/cosmos/cosmos-sdk/types.Uint\310\336\037\001'
  _OBSERVEDTXVOTER.fields_by_name['tx_id']._options = None
  _OBSERVEDTXVOTER.fields_by_name['tx_id']._serialized_options = b'\372\336\037)gitlab.com/thorchain/thornode/common.TxID\342\336\037\004TxID'
  _OBSERVEDTXVOTER.fields_by_name['tx']._options = None
  _OBSERVEDTXVOTER.fields_by_name['tx']._serialized_options = b'\310\336\037\000'
  _OBSERVEDTXVOTER.fields_by_name['txs']._options = None
  _OBSERVEDTXVOTER.fields_by_name['txs']._serialized_options = b'\252\337\037\013ObservedTxs\310\336\037\000'
  _OBSERVEDTXVOTER.fields_by_name['actions']._options = None
  _OBSERVEDTXVOTER.fields_by_name['actions']._serialized_options = b'\310\336\037\000'
  _OBSERVEDTXVOTER.fields_by_name['out_txs']._options = None
  _OBSERVEDTXVOTER.fields_by_name['out_txs']._serialized_options = b'\252\337\037(gitlab.com/thorchain/thornode/common.Txs\310\336\037\000'
  _STATUS._serialized_start=962
  _STATUS._serialized_end=1010
  _OBSERVEDTX._serialized_start=171
  _OBSERVEDTX._serialized_end=552
  _OBSERVEDTXVOTER._serialized_start=555
  _OBSERVEDTXVOTER._serialized_end=960
# @@protoc_insertion_point(module_scope)
