"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys
import thorchain.v1.common.common_pb2

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class TxOutItem(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CHAIN_FIELD_NUMBER: builtins.int
    TO_ADDRESS_FIELD_NUMBER: builtins.int
    VAULT_PUB_KEY_FIELD_NUMBER: builtins.int
    COIN_FIELD_NUMBER: builtins.int
    MEMO_FIELD_NUMBER: builtins.int
    MAX_GAS_FIELD_NUMBER: builtins.int
    GAS_RATE_FIELD_NUMBER: builtins.int
    IN_HASH_FIELD_NUMBER: builtins.int
    OUT_HASH_FIELD_NUMBER: builtins.int
    MODULE_NAME_FIELD_NUMBER: builtins.int
    AGGREGATOR_FIELD_NUMBER: builtins.int
    AGGREGATOR_TARGET_ASSET_FIELD_NUMBER: builtins.int
    AGGREGATOR_TARGET_LIMIT_FIELD_NUMBER: builtins.int
    chain: builtins.str
    to_address: builtins.str
    vault_pub_key: builtins.str
    @property
    def coin(self) -> thorchain.v1.common.common_pb2.Coin: ...
    memo: builtins.str
    @property
    def max_gas(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[thorchain.v1.common.common_pb2.Coin]: ...
    gas_rate: builtins.int
    in_hash: builtins.str
    out_hash: builtins.str
    module_name: builtins.str
    aggregator: builtins.str
    aggregator_target_asset: builtins.str
    aggregator_target_limit: builtins.str
    def __init__(
        self,
        *,
        chain: builtins.str = ...,
        to_address: builtins.str = ...,
        vault_pub_key: builtins.str = ...,
        coin: thorchain.v1.common.common_pb2.Coin | None = ...,
        memo: builtins.str = ...,
        max_gas: collections.abc.Iterable[thorchain.v1.common.common_pb2.Coin] | None = ...,
        gas_rate: builtins.int = ...,
        in_hash: builtins.str = ...,
        out_hash: builtins.str = ...,
        module_name: builtins.str = ...,
        aggregator: builtins.str = ...,
        aggregator_target_asset: builtins.str = ...,
        aggregator_target_limit: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["coin", b"coin"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["aggregator", b"aggregator", "aggregator_target_asset", b"aggregator_target_asset", "aggregator_target_limit", b"aggregator_target_limit", "chain", b"chain", "coin", b"coin", "gas_rate", b"gas_rate", "in_hash", b"in_hash", "max_gas", b"max_gas", "memo", b"memo", "module_name", b"module_name", "out_hash", b"out_hash", "to_address", b"to_address", "vault_pub_key", b"vault_pub_key"]) -> None: ...

global___TxOutItem = TxOutItem

@typing_extensions.final
class TxOut(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEIGHT_FIELD_NUMBER: builtins.int
    TX_ARRAY_FIELD_NUMBER: builtins.int
    height: builtins.int
    @property
    def tx_array(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TxOutItem]: ...
    def __init__(
        self,
        *,
        height: builtins.int = ...,
        tx_array: collections.abc.Iterable[global___TxOutItem] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["height", b"height", "tx_array", b"tx_array"]) -> None: ...

global___TxOut = TxOut
