# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: thorchain/v1/x/thorchain/types/type_pol.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-thorchain/v1/x/thorchain/types/type_pol.proto\x12\x05types\x1a\x14gogoproto/gogo.proto\"\xaa\x01\n\x16ProtocolOwnedLiquidity\x12G\n\x0erune_deposited\x18\x01 \x01(\tB/\xda\xde\x1f\'github.com/cosmos/cosmos-sdk/types.Uint\xc8\xde\x1f\x00\x12G\n\x0erune_withdrawn\x18\x02 \x01(\tB/\xda\xde\x1f\'github.com/cosmos/cosmos-sdk/types.Uint\xc8\xde\x1f\x00\x42\x31Z/gitlab.com/thorchain/thornode/x/thorchain/typesb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'thorchain.v1.x.thorchain.types.type_pol_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z/gitlab.com/thorchain/thornode/x/thorchain/types'
  _PROTOCOLOWNEDLIQUIDITY.fields_by_name['rune_deposited']._options = None
  _PROTOCOLOWNEDLIQUIDITY.fields_by_name['rune_deposited']._serialized_options = b'\332\336\037\'github.com/cosmos/cosmos-sdk/types.Uint\310\336\037\000'
  _PROTOCOLOWNEDLIQUIDITY.fields_by_name['rune_withdrawn']._options = None
  _PROTOCOLOWNEDLIQUIDITY.fields_by_name['rune_withdrawn']._serialized_options = b'\332\336\037\'github.com/cosmos/cosmos-sdk/types.Uint\310\336\037\000'
  _PROTOCOLOWNEDLIQUIDITY._serialized_start=79
  _PROTOCOLOWNEDLIQUIDITY._serialized_end=249
# @@protoc_insertion_point(module_scope)
