# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: thorchain/v1/x/thorchain/types/type_network.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1thorchain/v1/x/thorchain/types/type_network.proto\x12\x05types\x1a\x14gogoproto/gogo.proto\"\xe6\x02\n\x07Network\x12I\n\x10\x62ond_reward_rune\x18\x01 \x01(\tB/\xda\xde\x1f\'github.com/cosmos/cosmos-sdk/types.Uint\xc8\xde\x1f\x00\x12I\n\x10total_bond_units\x18\x02 \x01(\tB/\xda\xde\x1f\'github.com/cosmos/cosmos-sdk/types.Uint\xc8\xde\x1f\x00\x12I\n\x10\x62urned_bep2_rune\x18\x03 \x01(\tB/\xda\xde\x1f\'github.com/cosmos/cosmos-sdk/types.Uint\xc8\xde\x1f\x00\x12J\n\x11\x62urned_erc20_rune\x18\x04 \x01(\tB/\xda\xde\x1f\'github.com/cosmos/cosmos-sdk/types.Uint\xc8\xde\x1f\x00\x12\x15\n\rLPIncomeSplit\x18\x05 \x01(\x03\x12\x17\n\x0fNodeIncomeSplit\x18\x06 \x01(\x03\x42\x31Z/gitlab.com/thorchain/thornode/x/thorchain/typesb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'thorchain.v1.x.thorchain.types.type_network_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z/gitlab.com/thorchain/thornode/x/thorchain/types'
  _NETWORK.fields_by_name['bond_reward_rune']._options = None
  _NETWORK.fields_by_name['bond_reward_rune']._serialized_options = b'\332\336\037\'github.com/cosmos/cosmos-sdk/types.Uint\310\336\037\000'
  _NETWORK.fields_by_name['total_bond_units']._options = None
  _NETWORK.fields_by_name['total_bond_units']._serialized_options = b'\332\336\037\'github.com/cosmos/cosmos-sdk/types.Uint\310\336\037\000'
  _NETWORK.fields_by_name['burned_bep2_rune']._options = None
  _NETWORK.fields_by_name['burned_bep2_rune']._serialized_options = b'\332\336\037\'github.com/cosmos/cosmos-sdk/types.Uint\310\336\037\000'
  _NETWORK.fields_by_name['burned_erc20_rune']._options = None
  _NETWORK.fields_by_name['burned_erc20_rune']._serialized_options = b'\332\336\037\'github.com/cosmos/cosmos-sdk/types.Uint\310\336\037\000'
  _NETWORK._serialized_start=83
  _NETWORK._serialized_end=441
# @@protoc_insertion_point(module_scope)
