"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import thorchain.v1.common.common_pb2
import thorchain.v1.x.thorchain.types.type_pool_pb2
import thorchain.v1.x.thorchain.types.type_reserve_contributor_pb2
import thorchain.v1.x.thorchain.types.type_tx_out_pb2
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _PendingLiquidityType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _PendingLiquidityTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_PendingLiquidityType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    add: _PendingLiquidityType.ValueType  # 0
    withdraw: _PendingLiquidityType.ValueType  # 1

class PendingLiquidityType(_PendingLiquidityType, metaclass=_PendingLiquidityTypeEnumTypeWrapper): ...

add: PendingLiquidityType.ValueType  # 0
withdraw: PendingLiquidityType.ValueType  # 1
global___PendingLiquidityType = PendingLiquidityType

class _BondType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _BondTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_BondType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    bond_paid: _BondType.ValueType  # 0
    bond_returned: _BondType.ValueType  # 1
    bond_reward: _BondType.ValueType  # 2
    bond_cost: _BondType.ValueType  # 3

class BondType(_BondType, metaclass=_BondTypeEnumTypeWrapper): ...

bond_paid: BondType.ValueType  # 0
bond_returned: BondType.ValueType  # 1
bond_reward: BondType.ValueType  # 2
bond_cost: BondType.ValueType  # 3
global___BondType = BondType

class _MintBurnSupplyType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _MintBurnSupplyTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_MintBurnSupplyType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    mint: _MintBurnSupplyType.ValueType  # 0
    burn: _MintBurnSupplyType.ValueType  # 1

class MintBurnSupplyType(_MintBurnSupplyType, metaclass=_MintBurnSupplyTypeEnumTypeWrapper): ...

mint: MintBurnSupplyType.ValueType  # 0
burn: MintBurnSupplyType.ValueType  # 1
global___MintBurnSupplyType = MintBurnSupplyType

@typing_extensions.final
class PoolMod(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ASSET_FIELD_NUMBER: builtins.int
    RUNE_AMT_FIELD_NUMBER: builtins.int
    RUNE_ADD_FIELD_NUMBER: builtins.int
    ASSET_AMT_FIELD_NUMBER: builtins.int
    ASSET_ADD_FIELD_NUMBER: builtins.int
    @property
    def asset(self) -> thorchain.v1.common.common_pb2.Asset: ...
    rune_amt: builtins.str
    rune_add: builtins.bool
    asset_amt: builtins.str
    asset_add: builtins.bool
    def __init__(
        self,
        *,
        asset: thorchain.v1.common.common_pb2.Asset | None = ...,
        rune_amt: builtins.str = ...,
        rune_add: builtins.bool = ...,
        asset_amt: builtins.str = ...,
        asset_add: builtins.bool = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["asset", b"asset"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["asset", b"asset", "asset_add", b"asset_add", "asset_amt", b"asset_amt", "rune_add", b"rune_add", "rune_amt", b"rune_amt"]) -> None: ...

global___PoolMod = PoolMod

@typing_extensions.final
class EventLimitOrder(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SOURCE_FIELD_NUMBER: builtins.int
    TARGET_FIELD_NUMBER: builtins.int
    TX_ID_FIELD_NUMBER: builtins.int
    @property
    def source(self) -> thorchain.v1.common.common_pb2.Coin: ...
    @property
    def target(self) -> thorchain.v1.common.common_pb2.Coin: ...
    tx_id: builtins.str
    def __init__(
        self,
        *,
        source: thorchain.v1.common.common_pb2.Coin | None = ...,
        target: thorchain.v1.common.common_pb2.Coin | None = ...,
        tx_id: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["source", b"source", "target", b"target"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["source", b"source", "target", b"target", "tx_id", b"tx_id"]) -> None: ...

global___EventLimitOrder = EventLimitOrder

@typing_extensions.final
class EventSwap(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    POOL_FIELD_NUMBER: builtins.int
    SWAP_TARGET_FIELD_NUMBER: builtins.int
    SWAP_SLIP_FIELD_NUMBER: builtins.int
    LIQUIDITY_FEE_FIELD_NUMBER: builtins.int
    LIQUIDITY_FEE_IN_RUNE_FIELD_NUMBER: builtins.int
    IN_TX_FIELD_NUMBER: builtins.int
    OUT_TXS_FIELD_NUMBER: builtins.int
    EMIT_ASSET_FIELD_NUMBER: builtins.int
    SYNTH_UNITS_FIELD_NUMBER: builtins.int
    @property
    def pool(self) -> thorchain.v1.common.common_pb2.Asset: ...
    swap_target: builtins.str
    swap_slip: builtins.str
    liquidity_fee: builtins.str
    liquidity_fee_in_rune: builtins.str
    @property
    def in_tx(self) -> thorchain.v1.common.common_pb2.Tx: ...
    @property
    def out_txs(self) -> thorchain.v1.common.common_pb2.Tx: ...
    @property
    def emit_asset(self) -> thorchain.v1.common.common_pb2.Coin: ...
    synth_units: builtins.str
    def __init__(
        self,
        *,
        pool: thorchain.v1.common.common_pb2.Asset | None = ...,
        swap_target: builtins.str = ...,
        swap_slip: builtins.str = ...,
        liquidity_fee: builtins.str = ...,
        liquidity_fee_in_rune: builtins.str = ...,
        in_tx: thorchain.v1.common.common_pb2.Tx | None = ...,
        out_txs: thorchain.v1.common.common_pb2.Tx | None = ...,
        emit_asset: thorchain.v1.common.common_pb2.Coin | None = ...,
        synth_units: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["emit_asset", b"emit_asset", "in_tx", b"in_tx", "out_txs", b"out_txs", "pool", b"pool"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["emit_asset", b"emit_asset", "in_tx", b"in_tx", "liquidity_fee", b"liquidity_fee", "liquidity_fee_in_rune", b"liquidity_fee_in_rune", "out_txs", b"out_txs", "pool", b"pool", "swap_slip", b"swap_slip", "swap_target", b"swap_target", "synth_units", b"synth_units"]) -> None: ...

global___EventSwap = EventSwap

@typing_extensions.final
class EventAddLiquidity(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    POOL_FIELD_NUMBER: builtins.int
    PROVIDER_UNITS_FIELD_NUMBER: builtins.int
    RUNE_ADDRESS_FIELD_NUMBER: builtins.int
    RUNE_AMOUNT_FIELD_NUMBER: builtins.int
    ASSET_AMOUNT_FIELD_NUMBER: builtins.int
    RUNE_TX_ID_FIELD_NUMBER: builtins.int
    ASSET_TX_ID_FIELD_NUMBER: builtins.int
    ASSET_ADDRESS_FIELD_NUMBER: builtins.int
    @property
    def pool(self) -> thorchain.v1.common.common_pb2.Asset: ...
    provider_units: builtins.str
    rune_address: builtins.str
    rune_amount: builtins.str
    asset_amount: builtins.str
    rune_tx_id: builtins.str
    asset_tx_id: builtins.str
    asset_address: builtins.str
    def __init__(
        self,
        *,
        pool: thorchain.v1.common.common_pb2.Asset | None = ...,
        provider_units: builtins.str = ...,
        rune_address: builtins.str = ...,
        rune_amount: builtins.str = ...,
        asset_amount: builtins.str = ...,
        rune_tx_id: builtins.str = ...,
        asset_tx_id: builtins.str = ...,
        asset_address: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["pool", b"pool"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["asset_address", b"asset_address", "asset_amount", b"asset_amount", "asset_tx_id", b"asset_tx_id", "pool", b"pool", "provider_units", b"provider_units", "rune_address", b"rune_address", "rune_amount", b"rune_amount", "rune_tx_id", b"rune_tx_id"]) -> None: ...

global___EventAddLiquidity = EventAddLiquidity

@typing_extensions.final
class EventWithdraw(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    POOL_FIELD_NUMBER: builtins.int
    PROVIDER_UNITS_FIELD_NUMBER: builtins.int
    BASIS_POINTS_FIELD_NUMBER: builtins.int
    ASYMMETRY_FIELD_NUMBER: builtins.int
    IN_TX_FIELD_NUMBER: builtins.int
    EMIT_ASSET_FIELD_NUMBER: builtins.int
    EMIT_RUNE_FIELD_NUMBER: builtins.int
    IMP_LOSS_PROTECTION_FIELD_NUMBER: builtins.int
    @property
    def pool(self) -> thorchain.v1.common.common_pb2.Asset: ...
    provider_units: builtins.str
    basis_points: builtins.int
    asymmetry: builtins.bytes
    @property
    def in_tx(self) -> thorchain.v1.common.common_pb2.Tx: ...
    emit_asset: builtins.str
    emit_rune: builtins.str
    imp_loss_protection: builtins.str
    def __init__(
        self,
        *,
        pool: thorchain.v1.common.common_pb2.Asset | None = ...,
        provider_units: builtins.str = ...,
        basis_points: builtins.int = ...,
        asymmetry: builtins.bytes = ...,
        in_tx: thorchain.v1.common.common_pb2.Tx | None = ...,
        emit_asset: builtins.str = ...,
        emit_rune: builtins.str = ...,
        imp_loss_protection: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["in_tx", b"in_tx", "pool", b"pool"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["asymmetry", b"asymmetry", "basis_points", b"basis_points", "emit_asset", b"emit_asset", "emit_rune", b"emit_rune", "imp_loss_protection", b"imp_loss_protection", "in_tx", b"in_tx", "pool", b"pool", "provider_units", b"provider_units"]) -> None: ...

global___EventWithdraw = EventWithdraw

@typing_extensions.final
class EventPendingLiquidity(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    POOL_FIELD_NUMBER: builtins.int
    PENDING_TYPE_FIELD_NUMBER: builtins.int
    RUNE_ADDRESS_FIELD_NUMBER: builtins.int
    RUNE_AMOUNT_FIELD_NUMBER: builtins.int
    ASSET_ADDRESS_FIELD_NUMBER: builtins.int
    ASSET_AMOUNT_FIELD_NUMBER: builtins.int
    RUNE_TX_ID_FIELD_NUMBER: builtins.int
    ASSET_TX_ID_FIELD_NUMBER: builtins.int
    @property
    def pool(self) -> thorchain.v1.common.common_pb2.Asset: ...
    pending_type: global___PendingLiquidityType.ValueType
    rune_address: builtins.str
    rune_amount: builtins.str
    asset_address: builtins.str
    asset_amount: builtins.str
    rune_tx_id: builtins.str
    asset_tx_id: builtins.str
    def __init__(
        self,
        *,
        pool: thorchain.v1.common.common_pb2.Asset | None = ...,
        pending_type: global___PendingLiquidityType.ValueType = ...,
        rune_address: builtins.str = ...,
        rune_amount: builtins.str = ...,
        asset_address: builtins.str = ...,
        asset_amount: builtins.str = ...,
        rune_tx_id: builtins.str = ...,
        asset_tx_id: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["pool", b"pool"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["asset_address", b"asset_address", "asset_amount", b"asset_amount", "asset_tx_id", b"asset_tx_id", "pending_type", b"pending_type", "pool", b"pool", "rune_address", b"rune_address", "rune_amount", b"rune_amount", "rune_tx_id", b"rune_tx_id"]) -> None: ...

global___EventPendingLiquidity = EventPendingLiquidity

@typing_extensions.final
class EventDonate(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    POOL_FIELD_NUMBER: builtins.int
    IN_TX_FIELD_NUMBER: builtins.int
    @property
    def pool(self) -> thorchain.v1.common.common_pb2.Asset: ...
    @property
    def in_tx(self) -> thorchain.v1.common.common_pb2.Tx: ...
    def __init__(
        self,
        *,
        pool: thorchain.v1.common.common_pb2.Asset | None = ...,
        in_tx: thorchain.v1.common.common_pb2.Tx | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["in_tx", b"in_tx", "pool", b"pool"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["in_tx", b"in_tx", "pool", b"pool"]) -> None: ...

global___EventDonate = EventDonate

@typing_extensions.final
class EventPool(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    POOL_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    @property
    def pool(self) -> thorchain.v1.common.common_pb2.Asset: ...
    Status: thorchain.v1.x.thorchain.types.type_pool_pb2.PoolStatus.ValueType
    def __init__(
        self,
        *,
        pool: thorchain.v1.common.common_pb2.Asset | None = ...,
        Status: thorchain.v1.x.thorchain.types.type_pool_pb2.PoolStatus.ValueType = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["pool", b"pool"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["Status", b"Status", "pool", b"pool"]) -> None: ...

global___EventPool = EventPool

@typing_extensions.final
class PoolAmt(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ASSET_FIELD_NUMBER: builtins.int
    AMOUNT_FIELD_NUMBER: builtins.int
    @property
    def asset(self) -> thorchain.v1.common.common_pb2.Asset: ...
    amount: builtins.int
    def __init__(
        self,
        *,
        asset: thorchain.v1.common.common_pb2.Asset | None = ...,
        amount: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["asset", b"asset"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["amount", b"amount", "asset", b"asset"]) -> None: ...

global___PoolAmt = PoolAmt

@typing_extensions.final
class EventRewards(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BOND_REWARD_FIELD_NUMBER: builtins.int
    POOL_REWARDS_FIELD_NUMBER: builtins.int
    bond_reward: builtins.str
    @property
    def pool_rewards(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___PoolAmt]: ...
    def __init__(
        self,
        *,
        bond_reward: builtins.str = ...,
        pool_rewards: collections.abc.Iterable[global___PoolAmt] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["bond_reward", b"bond_reward", "pool_rewards", b"pool_rewards"]) -> None: ...

global___EventRewards = EventRewards

@typing_extensions.final
class EventRefund(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CODE_FIELD_NUMBER: builtins.int
    REASON_FIELD_NUMBER: builtins.int
    IN_TX_FIELD_NUMBER: builtins.int
    FEE_FIELD_NUMBER: builtins.int
    code: builtins.int
    reason: builtins.str
    @property
    def in_tx(self) -> thorchain.v1.common.common_pb2.Tx: ...
    @property
    def fee(self) -> thorchain.v1.common.common_pb2.Fee: ...
    def __init__(
        self,
        *,
        code: builtins.int = ...,
        reason: builtins.str = ...,
        in_tx: thorchain.v1.common.common_pb2.Tx | None = ...,
        fee: thorchain.v1.common.common_pb2.Fee | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["fee", b"fee", "in_tx", b"in_tx"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["code", b"code", "fee", b"fee", "in_tx", b"in_tx", "reason", b"reason"]) -> None: ...

global___EventRefund = EventRefund

@typing_extensions.final
class EventBond(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AMOUNT_FIELD_NUMBER: builtins.int
    BOND_TYPE_FIELD_NUMBER: builtins.int
    TX_IN_FIELD_NUMBER: builtins.int
    amount: builtins.str
    bond_type: global___BondType.ValueType
    @property
    def tx_in(self) -> thorchain.v1.common.common_pb2.Tx: ...
    def __init__(
        self,
        *,
        amount: builtins.str = ...,
        bond_type: global___BondType.ValueType = ...,
        tx_in: thorchain.v1.common.common_pb2.Tx | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["tx_in", b"tx_in"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["amount", b"amount", "bond_type", b"bond_type", "tx_in", b"tx_in"]) -> None: ...

global___EventBond = EventBond

@typing_extensions.final
class GasPool(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ASSET_FIELD_NUMBER: builtins.int
    RUNE_AMT_FIELD_NUMBER: builtins.int
    ASSET_AMT_FIELD_NUMBER: builtins.int
    COUNT_FIELD_NUMBER: builtins.int
    @property
    def asset(self) -> thorchain.v1.common.common_pb2.Asset: ...
    rune_amt: builtins.str
    asset_amt: builtins.str
    count: builtins.int
    def __init__(
        self,
        *,
        asset: thorchain.v1.common.common_pb2.Asset | None = ...,
        rune_amt: builtins.str = ...,
        asset_amt: builtins.str = ...,
        count: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["asset", b"asset"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["asset", b"asset", "asset_amt", b"asset_amt", "count", b"count", "rune_amt", b"rune_amt"]) -> None: ...

global___GasPool = GasPool

@typing_extensions.final
class EventGas(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    POOLS_FIELD_NUMBER: builtins.int
    @property
    def pools(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___GasPool]: ...
    def __init__(
        self,
        *,
        pools: collections.abc.Iterable[global___GasPool] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["pools", b"pools"]) -> None: ...

global___EventGas = EventGas

@typing_extensions.final
class EventReserve(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESERVE_CONTRIBUTOR_FIELD_NUMBER: builtins.int
    IN_TX_FIELD_NUMBER: builtins.int
    @property
    def reserve_contributor(self) -> thorchain.v1.x.thorchain.types.type_reserve_contributor_pb2.ReserveContributor: ...
    @property
    def in_tx(self) -> thorchain.v1.common.common_pb2.Tx: ...
    def __init__(
        self,
        *,
        reserve_contributor: thorchain.v1.x.thorchain.types.type_reserve_contributor_pb2.ReserveContributor | None = ...,
        in_tx: thorchain.v1.common.common_pb2.Tx | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["in_tx", b"in_tx", "reserve_contributor", b"reserve_contributor"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["in_tx", b"in_tx", "reserve_contributor", b"reserve_contributor"]) -> None: ...

global___EventReserve = EventReserve

@typing_extensions.final
class EventScheduledOutbound(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OUT_TX_FIELD_NUMBER: builtins.int
    @property
    def out_tx(self) -> thorchain.v1.x.thorchain.types.type_tx_out_pb2.TxOutItem: ...
    def __init__(
        self,
        *,
        out_tx: thorchain.v1.x.thorchain.types.type_tx_out_pb2.TxOutItem | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["out_tx", b"out_tx"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["out_tx", b"out_tx"]) -> None: ...

global___EventScheduledOutbound = EventScheduledOutbound

@typing_extensions.final
class EventSecurity(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MSG_FIELD_NUMBER: builtins.int
    TX_FIELD_NUMBER: builtins.int
    msg: builtins.str
    @property
    def tx(self) -> thorchain.v1.common.common_pb2.Tx: ...
    def __init__(
        self,
        *,
        msg: builtins.str = ...,
        tx: thorchain.v1.common.common_pb2.Tx | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["tx", b"tx"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["msg", b"msg", "tx", b"tx"]) -> None: ...

global___EventSecurity = EventSecurity

@typing_extensions.final
class EventSlash(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    POOL_FIELD_NUMBER: builtins.int
    SLASH_AMOUNT_FIELD_NUMBER: builtins.int
    @property
    def pool(self) -> thorchain.v1.common.common_pb2.Asset: ...
    @property
    def slash_amount(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___PoolAmt]: ...
    def __init__(
        self,
        *,
        pool: thorchain.v1.common.common_pb2.Asset | None = ...,
        slash_amount: collections.abc.Iterable[global___PoolAmt] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["pool", b"pool"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["pool", b"pool", "slash_amount", b"slash_amount"]) -> None: ...

global___EventSlash = EventSlash

@typing_extensions.final
class EventErrata(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TX_ID_FIELD_NUMBER: builtins.int
    POOLS_FIELD_NUMBER: builtins.int
    tx_id: builtins.str
    @property
    def pools(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___PoolMod]: ...
    def __init__(
        self,
        *,
        tx_id: builtins.str = ...,
        pools: collections.abc.Iterable[global___PoolMod] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["pools", b"pools", "tx_id", b"tx_id"]) -> None: ...

global___EventErrata = EventErrata

@typing_extensions.final
class EventFee(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TX_ID_FIELD_NUMBER: builtins.int
    FEE_FIELD_NUMBER: builtins.int
    SYNTH_UNITS_FIELD_NUMBER: builtins.int
    tx_id: builtins.str
    @property
    def fee(self) -> thorchain.v1.common.common_pb2.Fee: ...
    synth_units: builtins.str
    def __init__(
        self,
        *,
        tx_id: builtins.str = ...,
        fee: thorchain.v1.common.common_pb2.Fee | None = ...,
        synth_units: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["fee", b"fee"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["fee", b"fee", "synth_units", b"synth_units", "tx_id", b"tx_id"]) -> None: ...

global___EventFee = EventFee

@typing_extensions.final
class EventOutbound(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IN_TX_ID_FIELD_NUMBER: builtins.int
    TX_FIELD_NUMBER: builtins.int
    in_tx_id: builtins.str
    @property
    def tx(self) -> thorchain.v1.common.common_pb2.Tx: ...
    def __init__(
        self,
        *,
        in_tx_id: builtins.str = ...,
        tx: thorchain.v1.common.common_pb2.Tx | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["tx", b"tx"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["in_tx_id", b"in_tx_id", "tx", b"tx"]) -> None: ...

global___EventOutbound = EventOutbound

@typing_extensions.final
class EventTssKeygenMetric(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PUB_KEY_FIELD_NUMBER: builtins.int
    MEDIAN_DURATION_MS_FIELD_NUMBER: builtins.int
    pub_key: builtins.str
    median_duration_ms: builtins.int
    def __init__(
        self,
        *,
        pub_key: builtins.str = ...,
        median_duration_ms: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["median_duration_ms", b"median_duration_ms", "pub_key", b"pub_key"]) -> None: ...

global___EventTssKeygenMetric = EventTssKeygenMetric

@typing_extensions.final
class EventTssKeysignMetric(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TX_ID_FIELD_NUMBER: builtins.int
    MEDIAN_DURATION_MS_FIELD_NUMBER: builtins.int
    tx_id: builtins.str
    median_duration_ms: builtins.int
    def __init__(
        self,
        *,
        tx_id: builtins.str = ...,
        median_duration_ms: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["median_duration_ms", b"median_duration_ms", "tx_id", b"tx_id"]) -> None: ...

global___EventTssKeysignMetric = EventTssKeysignMetric

@typing_extensions.final
class EventSlashPoint(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NODE_ADDRESS_FIELD_NUMBER: builtins.int
    SLASH_POINTS_FIELD_NUMBER: builtins.int
    REASON_FIELD_NUMBER: builtins.int
    node_address: builtins.bytes
    slash_points: builtins.int
    reason: builtins.str
    def __init__(
        self,
        *,
        node_address: builtins.bytes = ...,
        slash_points: builtins.int = ...,
        reason: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["node_address", b"node_address", "reason", b"reason", "slash_points", b"slash_points"]) -> None: ...

global___EventSlashPoint = EventSlashPoint

@typing_extensions.final
class EventPoolBalanceChanged(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    POOL_CHANGE_FIELD_NUMBER: builtins.int
    REASON_FIELD_NUMBER: builtins.int
    @property
    def pool_change(self) -> global___PoolMod: ...
    reason: builtins.str
    def __init__(
        self,
        *,
        pool_change: global___PoolMod | None = ...,
        reason: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["pool_change", b"pool_change"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["pool_change", b"pool_change", "reason", b"reason"]) -> None: ...

global___EventPoolBalanceChanged = EventPoolBalanceChanged

@typing_extensions.final
class EventSwitch(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TO_ADDRESS_FIELD_NUMBER: builtins.int
    FROM_ADDRESS_FIELD_NUMBER: builtins.int
    BURN_FIELD_NUMBER: builtins.int
    TX_ID_FIELD_NUMBER: builtins.int
    to_address: builtins.bytes
    from_address: builtins.str
    @property
    def burn(self) -> thorchain.v1.common.common_pb2.Coin: ...
    tx_id: builtins.str
    def __init__(
        self,
        *,
        to_address: builtins.bytes = ...,
        from_address: builtins.str = ...,
        burn: thorchain.v1.common.common_pb2.Coin | None = ...,
        tx_id: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["burn", b"burn"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["burn", b"burn", "from_address", b"from_address", "to_address", b"to_address", "tx_id", b"tx_id"]) -> None: ...

global___EventSwitch = EventSwitch

@typing_extensions.final
class EventSwitchV87(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TO_ADDRESS_FIELD_NUMBER: builtins.int
    FROM_ADDRESS_FIELD_NUMBER: builtins.int
    BURN_FIELD_NUMBER: builtins.int
    TX_ID_FIELD_NUMBER: builtins.int
    MINT_FIELD_NUMBER: builtins.int
    to_address: builtins.bytes
    from_address: builtins.str
    @property
    def burn(self) -> thorchain.v1.common.common_pb2.Coin: ...
    tx_id: builtins.str
    mint: builtins.str
    def __init__(
        self,
        *,
        to_address: builtins.bytes = ...,
        from_address: builtins.str = ...,
        burn: thorchain.v1.common.common_pb2.Coin | None = ...,
        tx_id: builtins.str = ...,
        mint: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["burn", b"burn"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["burn", b"burn", "from_address", b"from_address", "mint", b"mint", "to_address", b"to_address", "tx_id", b"tx_id"]) -> None: ...

global___EventSwitchV87 = EventSwitchV87

@typing_extensions.final
class EventMintBurn(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUPPLY_FIELD_NUMBER: builtins.int
    DENOM_FIELD_NUMBER: builtins.int
    AMOUNT_FIELD_NUMBER: builtins.int
    REASON_FIELD_NUMBER: builtins.int
    supply: global___MintBurnSupplyType.ValueType
    denom: builtins.str
    amount: builtins.str
    reason: builtins.str
    def __init__(
        self,
        *,
        supply: global___MintBurnSupplyType.ValueType = ...,
        denom: builtins.str = ...,
        amount: builtins.str = ...,
        reason: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["amount", b"amount", "denom", b"denom", "reason", b"reason", "supply", b"supply"]) -> None: ...

global___EventMintBurn = EventMintBurn

@typing_extensions.final
class EventLoanOpen(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    COLLATERAL_UP_FIELD_NUMBER: builtins.int
    COLLATERAL_ASSET_FIELD_NUMBER: builtins.int
    COLLATERALIZATION_RATIO_FIELD_NUMBER: builtins.int
    DEBT_UP_FIELD_NUMBER: builtins.int
    OWNER_FIELD_NUMBER: builtins.int
    TARGET_ASSET_FIELD_NUMBER: builtins.int
    collateral_up: builtins.str
    @property
    def collateral_asset(self) -> thorchain.v1.common.common_pb2.Asset: ...
    collateralization_ratio: builtins.str
    debt_up: builtins.str
    owner: builtins.str
    @property
    def target_asset(self) -> thorchain.v1.common.common_pb2.Asset: ...
    def __init__(
        self,
        *,
        collateral_up: builtins.str = ...,
        collateral_asset: thorchain.v1.common.common_pb2.Asset | None = ...,
        collateralization_ratio: builtins.str = ...,
        debt_up: builtins.str = ...,
        owner: builtins.str = ...,
        target_asset: thorchain.v1.common.common_pb2.Asset | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["collateral_asset", b"collateral_asset", "target_asset", b"target_asset"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["collateral_asset", b"collateral_asset", "collateral_up", b"collateral_up", "collateralization_ratio", b"collateralization_ratio", "debt_up", b"debt_up", "owner", b"owner", "target_asset", b"target_asset"]) -> None: ...

global___EventLoanOpen = EventLoanOpen

@typing_extensions.final
class EventLoanRepayment(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    COLLATERAL_DOWN_FIELD_NUMBER: builtins.int
    COLLATERAL_ASSET_FIELD_NUMBER: builtins.int
    DEBT_DOWN_FIELD_NUMBER: builtins.int
    OWNER_FIELD_NUMBER: builtins.int
    collateral_down: builtins.str
    @property
    def collateral_asset(self) -> thorchain.v1.common.common_pb2.Asset: ...
    debt_down: builtins.str
    owner: builtins.str
    def __init__(
        self,
        *,
        collateral_down: builtins.str = ...,
        collateral_asset: thorchain.v1.common.common_pb2.Asset | None = ...,
        debt_down: builtins.str = ...,
        owner: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["collateral_asset", b"collateral_asset"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["collateral_asset", b"collateral_asset", "collateral_down", b"collateral_down", "debt_down", b"debt_down", "owner", b"owner"]) -> None: ...

global___EventLoanRepayment = EventLoanRepayment

@typing_extensions.final
class EventTHORName(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    CHAIN_FIELD_NUMBER: builtins.int
    ADDRESS_FIELD_NUMBER: builtins.int
    REGISTRATION_FEE_FIELD_NUMBER: builtins.int
    FUND_AMT_FIELD_NUMBER: builtins.int
    EXPIRE_FIELD_NUMBER: builtins.int
    OWNER_FIELD_NUMBER: builtins.int
    name: builtins.str
    chain: builtins.str
    address: builtins.str
    registration_fee: builtins.str
    fund_amt: builtins.str
    expire: builtins.int
    owner: builtins.bytes
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        chain: builtins.str = ...,
        address: builtins.str = ...,
        registration_fee: builtins.str = ...,
        fund_amt: builtins.str = ...,
        expire: builtins.int = ...,
        owner: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["address", b"address", "chain", b"chain", "expire", b"expire", "fund_amt", b"fund_amt", "name", b"name", "owner", b"owner", "registration_fee", b"registration_fee"]) -> None: ...

global___EventTHORName = EventTHORName

@typing_extensions.final
class EventSetMimir(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    KEY_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    key: builtins.str
    value: builtins.str
    def __init__(
        self,
        *,
        key: builtins.str = ...,
        value: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

global___EventSetMimir = EventSetMimir

@typing_extensions.final
class EventSetNodeMimir(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    KEY_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    ADDRESS_FIELD_NUMBER: builtins.int
    key: builtins.str
    value: builtins.str
    address: builtins.str
    def __init__(
        self,
        *,
        key: builtins.str = ...,
        value: builtins.str = ...,
        address: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["address", b"address", "key", b"key", "value", b"value"]) -> None: ...

global___EventSetNodeMimir = EventSetNodeMimir

@typing_extensions.final
class EventVersion(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VERSION_FIELD_NUMBER: builtins.int
    version: builtins.str
    def __init__(
        self,
        *,
        version: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["version", b"version"]) -> None: ...

global___EventVersion = EventVersion
