"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class NetworkFee(google.protobuf.message.Message):
    """NetworkFee represent the fee rate and typical transaction size outbound from
    THORNode This is to keep the information reported by bifrost For BTC chain,
    TransactionFeeRate should be sats/vbyte For Binance chain , given fee is
    fixed , thus for single coin , transaction size will be 1, and the rate
    should be 37500, for multiple coin , Transaction size should the number of
    coins
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CHAIN_FIELD_NUMBER: builtins.int
    TRANSACTION_SIZE_FIELD_NUMBER: builtins.int
    TRANSACTION_FEE_RATE_FIELD_NUMBER: builtins.int
    chain: builtins.str
    transaction_size: builtins.int
    transaction_fee_rate: builtins.int
    def __init__(
        self,
        *,
        chain: builtins.str = ...,
        transaction_size: builtins.int = ...,
        transaction_fee_rate: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["chain", b"chain", "transaction_fee_rate", b"transaction_fee_rate", "transaction_size", b"transaction_size"]) -> None: ...

global___NetworkFee = NetworkFee
