"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class Asset(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CHAIN_FIELD_NUMBER: builtins.int
    SYMBOL_FIELD_NUMBER: builtins.int
    TICKER_FIELD_NUMBER: builtins.int
    SYNTH_FIELD_NUMBER: builtins.int
    chain: builtins.str
    symbol: builtins.str
    ticker: builtins.str
    synth: builtins.bool
    def __init__(
        self,
        *,
        chain: builtins.str = ...,
        symbol: builtins.str = ...,
        ticker: builtins.str = ...,
        synth: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["chain", b"chain", "symbol", b"symbol", "synth", b"synth", "ticker", b"ticker"]) -> None: ...

global___Asset = Asset

@typing_extensions.final
class Coin(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ASSET_FIELD_NUMBER: builtins.int
    AMOUNT_FIELD_NUMBER: builtins.int
    DECIMALS_FIELD_NUMBER: builtins.int
    @property
    def asset(self) -> global___Asset: ...
    amount: builtins.str
    decimals: builtins.int
    def __init__(
        self,
        *,
        asset: global___Asset | None = ...,
        amount: builtins.str = ...,
        decimals: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["asset", b"asset"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["amount", b"amount", "asset", b"asset", "decimals", b"decimals"]) -> None: ...

global___Coin = Coin

@typing_extensions.final
class PubKeySet(google.protobuf.message.Message):
    """PubKeySet contains two pub keys , secp256k1 and ed25519"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SECP256K1_FIELD_NUMBER: builtins.int
    ED25519_FIELD_NUMBER: builtins.int
    secp256k1: builtins.str
    ed25519: builtins.str
    def __init__(
        self,
        *,
        secp256k1: builtins.str = ...,
        ed25519: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["ed25519", b"ed25519", "secp256k1", b"secp256k1"]) -> None: ...

global___PubKeySet = PubKeySet

@typing_extensions.final
class Tx(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    CHAIN_FIELD_NUMBER: builtins.int
    FROM_ADDRESS_FIELD_NUMBER: builtins.int
    TO_ADDRESS_FIELD_NUMBER: builtins.int
    COINS_FIELD_NUMBER: builtins.int
    GAS_FIELD_NUMBER: builtins.int
    MEMO_FIELD_NUMBER: builtins.int
    id: builtins.str
    chain: builtins.str
    from_address: builtins.str
    to_address: builtins.str
    @property
    def coins(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Coin]: ...
    @property
    def gas(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Coin]: ...
    memo: builtins.str
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        chain: builtins.str = ...,
        from_address: builtins.str = ...,
        to_address: builtins.str = ...,
        coins: collections.abc.Iterable[global___Coin] | None = ...,
        gas: collections.abc.Iterable[global___Coin] | None = ...,
        memo: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["chain", b"chain", "coins", b"coins", "from_address", b"from_address", "gas", b"gas", "id", b"id", "memo", b"memo", "to_address", b"to_address"]) -> None: ...

global___Tx = Tx

@typing_extensions.final
class Fee(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    COINS_FIELD_NUMBER: builtins.int
    POOL_DEDUCT_FIELD_NUMBER: builtins.int
    @property
    def coins(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Coin]: ...
    pool_deduct: builtins.str
    def __init__(
        self,
        *,
        coins: collections.abc.Iterable[global___Coin] | None = ...,
        pool_deduct: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["coins", b"coins", "pool_deduct", b"pool_deduct"]) -> None: ...

global___Fee = Fee

@typing_extensions.final
class ProtoUint(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUE_FIELD_NUMBER: builtins.int
    value: builtins.str
    def __init__(
        self,
        *,
        value: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["value", b"value"]) -> None: ...

global___ProtoUint = ProtoUint
