"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import gaia.wasm.v1beta1.tx_pb2
import grpc

class MsgStub:
    """Msg defines the oracle Msg service."""

    def __init__(self, channel: grpc.Channel) -> None: ...
    ExecuteContract: grpc.UnaryUnaryMultiCallable[
        gaia.wasm.v1beta1.tx_pb2.MsgExecuteContract,
        gaia.wasm.v1beta1.tx_pb2.MsgExecuteContractResponse,
    ]
    """Execute submits the given message data to a smart contract"""

class MsgServicer(metaclass=abc.ABCMeta):
    """Msg defines the oracle Msg service."""

    @abc.abstractmethod
    def ExecuteContract(
        self,
        request: gaia.wasm.v1beta1.tx_pb2.MsgExecuteContract,
        context: grpc.ServicerContext,
    ) -> gaia.wasm.v1beta1.tx_pb2.MsgExecuteContractResponse:
        """Execute submits the given message data to a smart contract"""

def add_MsgServicer_to_server(servicer: MsgServicer, server: grpc.Server) -> None: ...
