# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from gaia.wasm.v1beta1 import tx_pb2 as gaia_dot_wasm_dot_v1beta1_dot_tx__pb2


class MsgStub(object):
    """Msg defines the oracle Msg service.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteContract = channel.unary_unary(
                '/gaia.wasm.v1beta1.Msg/ExecuteContract',
                request_serializer=gaia_dot_wasm_dot_v1beta1_dot_tx__pb2.MsgExecuteContract.SerializeToString,
                response_deserializer=gaia_dot_wasm_dot_v1beta1_dot_tx__pb2.MsgExecuteContractResponse.FromString,
                )


class MsgServicer(object):
    """Msg defines the oracle Msg service.
    """

    def ExecuteContract(self, request, context):
        """Execute submits the given message data to a smart contract
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MsgServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteContract': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteContract,
                    request_deserializer=gaia_dot_wasm_dot_v1beta1_dot_tx__pb2.MsgExecuteContract.FromString,
                    response_serializer=gaia_dot_wasm_dot_v1beta1_dot_tx__pb2.MsgExecuteContractResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gaia.wasm.v1beta1.Msg', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Msg(object):
    """Msg defines the oracle Msg service.
    """

    @staticmethod
    def ExecuteContract(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gaia.wasm.v1beta1.Msg/ExecuteContract',
            gaia_dot_wasm_dot_v1beta1_dot_tx__pb2.MsgExecuteContract.SerializeToString,
            gaia_dot_wasm_dot_v1beta1_dot_tx__pb2.MsgExecuteContractResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
