# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gaia/wasm/v1beta1/tx.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from cosmos.base.v1beta1 import coin_pb2 as cosmos_dot_base_dot_v1beta1_dot_coin__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1agaia/wasm/v1beta1/tx.proto\x12\x11gaia.wasm.v1beta1\x1a\x14gogoproto/gogo.proto\x1a\x1e\x63osmos/base/v1beta1/coin.proto\"\x9d\x02\n\x12MsgExecuteContract\x12!\n\x06sender\x18\x01 \x01(\tB\x11\xf2\xde\x1f\ryaml:\"sender\"\x12%\n\x08\x63ontract\x18\x02 \x01(\tB\x13\xf2\xde\x1f\x0fyaml:\"contract\"\x12G\n\x0b\x65xecute_msg\x18\x03 \x01(\x0c\x42\x32\xf2\xde\x1f\x12yaml:\"execute_msg\"\xfa\xde\x1f\x18\x65ncoding/json.RawMessage\x12j\n\x05\x63oins\x18\x05 \x03(\x0b\x32\x19.cosmos.base.v1beta1.CoinB@\xf2\xde\x1f\x0cyaml:\"coins\"\xc8\xde\x1f\x00\xaa\xdf\x1f(github.com/cosmos/cosmos-sdk/types.Coins:\x08\xe8\xa0\x1f\x00\x88\xa0\x1f\x00\";\n\x1aMsgExecuteContractResponse\x12\x1d\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x42\x0f\xf2\xde\x1f\x0byaml:\"data\"2n\n\x03Msg\x12g\n\x0f\x45xecuteContract\x12%.gaia.wasm.v1beta1.MsgExecuteContract\x1a-.gaia.wasm.v1beta1.MsgExecuteContractResponseB$Z\"bifrost/pkg/chainclients/gaia/wasmb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gaia.wasm.v1beta1.tx_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\"bifrost/pkg/chainclients/gaia/wasm'
  _MSGEXECUTECONTRACT.fields_by_name['sender']._options = None
  _MSGEXECUTECONTRACT.fields_by_name['sender']._serialized_options = b'\362\336\037\ryaml:\"sender\"'
  _MSGEXECUTECONTRACT.fields_by_name['contract']._options = None
  _MSGEXECUTECONTRACT.fields_by_name['contract']._serialized_options = b'\362\336\037\017yaml:\"contract\"'
  _MSGEXECUTECONTRACT.fields_by_name['execute_msg']._options = None
  _MSGEXECUTECONTRACT.fields_by_name['execute_msg']._serialized_options = b'\362\336\037\022yaml:\"execute_msg\"\372\336\037\030encoding/json.RawMessage'
  _MSGEXECUTECONTRACT.fields_by_name['coins']._options = None
  _MSGEXECUTECONTRACT.fields_by_name['coins']._serialized_options = b'\362\336\037\014yaml:\"coins\"\310\336\037\000\252\337\037(github.com/cosmos/cosmos-sdk/types.Coins'
  _MSGEXECUTECONTRACT._options = None
  _MSGEXECUTECONTRACT._serialized_options = b'\350\240\037\000\210\240\037\000'
  _MSGEXECUTECONTRACTRESPONSE.fields_by_name['data']._options = None
  _MSGEXECUTECONTRACTRESPONSE.fields_by_name['data']._serialized_options = b'\362\336\037\013yaml:\"data\"'
  _MSGEXECUTECONTRACT._serialized_start=104
  _MSGEXECUTECONTRACT._serialized_end=389
  _MSGEXECUTECONTRACTRESPONSE._serialized_start=391
  _MSGEXECUTECONTRACTRESPONSE._serialized_end=450
  _MSG._serialized_start=452
  _MSG._serialized_end=562
# @@protoc_insertion_point(module_scope)
