"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys
import thorchain.v1.x.thorchain.types.msg_swap_pb2
import thorchain.v1.x.thorchain.types.type_chain_contract_pb2
import thorchain.v1.x.thorchain.types.type_liquidity_provider_pb2
import thorchain.v1.x.thorchain.types.type_loan_pb2
import thorchain.v1.x.thorchain.types.type_network_fee_pb2
import thorchain.v1.x.thorchain.types.type_network_pb2
import thorchain.v1.x.thorchain.types.type_node_account_pb2
import thorchain.v1.x.thorchain.types.type_observed_tx_pb2
import thorchain.v1.x.thorchain.types.type_pol_pb2
import thorchain.v1.x.thorchain.types.type_pool_pb2
import thorchain.v1.x.thorchain.types.type_reserve_contributor_pb2
import thorchain.v1.x.thorchain.types.type_thorname_pb2
import thorchain.v1.x.thorchain.types.type_tx_out_pb2
import thorchain.v1.x.thorchain.types.type_vault_pb2

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class lastChainHeight(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CHAIN_FIELD_NUMBER: builtins.int
    HEIGHT_FIELD_NUMBER: builtins.int
    chain: builtins.str
    height: builtins.int
    def __init__(
        self,
        *,
        chain: builtins.str = ...,
        height: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["chain", b"chain", "height", b"height"]) -> None: ...

global___lastChainHeight = lastChainHeight

@typing_extensions.final
class mimir(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    KEY_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    key: builtins.str
    value: builtins.int
    def __init__(
        self,
        *,
        key: builtins.str = ...,
        value: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

global___mimir = mimir

@typing_extensions.final
class GenesisState(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    POOLS_FIELD_NUMBER: builtins.int
    LIQUIDITY_PROVIDERS_FIELD_NUMBER: builtins.int
    OBSERVED_TX_IN_VOTERS_FIELD_NUMBER: builtins.int
    OBSERVED_TX_OUT_VOTERS_FIELD_NUMBER: builtins.int
    TX_OUTS_FIELD_NUMBER: builtins.int
    NODE_ACCOUNTS_FIELD_NUMBER: builtins.int
    VAULTS_FIELD_NUMBER: builtins.int
    RESERVE_FIELD_NUMBER: builtins.int
    LAST_SIGNED_HEIGHT_FIELD_NUMBER: builtins.int
    LAST_CHAIN_HEIGHTS_FIELD_NUMBER: builtins.int
    RESERVE_CONTRIBUTORS_FIELD_NUMBER: builtins.int
    NETWORK_FIELD_NUMBER: builtins.int
    MSG_SWAPS_FIELD_NUMBER: builtins.int
    NETWORK_FEES_FIELD_NUMBER: builtins.int
    CHAIN_CONTRACTS_FIELD_NUMBER: builtins.int
    THORNAMES_FIELD_NUMBER: builtins.int
    MIMIRS_FIELD_NUMBER: builtins.int
    STORE_VERSION_FIELD_NUMBER: builtins.int
    BOND_PROVIDERS_FIELD_NUMBER: builtins.int
    POL_FIELD_NUMBER: builtins.int
    LOANS_FIELD_NUMBER: builtins.int
    @property
    def pools(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[thorchain.v1.x.thorchain.types.type_pool_pb2.Pool]: ...
    @property
    def liquidity_providers(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[thorchain.v1.x.thorchain.types.type_liquidity_provider_pb2.LiquidityProvider]: ...
    @property
    def observed_tx_in_voters(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[thorchain.v1.x.thorchain.types.type_observed_tx_pb2.ObservedTxVoter]: ...
    @property
    def observed_tx_out_voters(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[thorchain.v1.x.thorchain.types.type_observed_tx_pb2.ObservedTxVoter]: ...
    @property
    def tx_outs(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[thorchain.v1.x.thorchain.types.type_tx_out_pb2.TxOut]: ...
    @property
    def node_accounts(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[thorchain.v1.x.thorchain.types.type_node_account_pb2.NodeAccount]: ...
    @property
    def vaults(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[thorchain.v1.x.thorchain.types.type_vault_pb2.Vault]: ...
    reserve: builtins.int
    last_signed_height: builtins.int
    @property
    def last_chain_heights(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___lastChainHeight]: ...
    @property
    def reserve_contributors(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[thorchain.v1.x.thorchain.types.type_reserve_contributor_pb2.ReserveContributor]: ...
    @property
    def network(self) -> thorchain.v1.x.thorchain.types.type_network_pb2.Network: ...
    @property
    def msg_swaps(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[thorchain.v1.x.thorchain.types.msg_swap_pb2.MsgSwap]: ...
    @property
    def network_fees(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[thorchain.v1.x.thorchain.types.type_network_fee_pb2.NetworkFee]: ...
    @property
    def chain_contracts(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[thorchain.v1.x.thorchain.types.type_chain_contract_pb2.ChainContract]: ...
    @property
    def THORNames(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[thorchain.v1.x.thorchain.types.type_thorname_pb2.THORName]: ...
    @property
    def mimirs(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___mimir]: ...
    store_version: builtins.int
    @property
    def bond_providers(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[thorchain.v1.x.thorchain.types.type_node_account_pb2.BondProviders]: ...
    @property
    def POL(self) -> thorchain.v1.x.thorchain.types.type_pol_pb2.ProtocolOwnedLiquidity: ...
    @property
    def loans(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[thorchain.v1.x.thorchain.types.type_loan_pb2.Loan]: ...
    def __init__(
        self,
        *,
        pools: collections.abc.Iterable[thorchain.v1.x.thorchain.types.type_pool_pb2.Pool] | None = ...,
        liquidity_providers: collections.abc.Iterable[thorchain.v1.x.thorchain.types.type_liquidity_provider_pb2.LiquidityProvider] | None = ...,
        observed_tx_in_voters: collections.abc.Iterable[thorchain.v1.x.thorchain.types.type_observed_tx_pb2.ObservedTxVoter] | None = ...,
        observed_tx_out_voters: collections.abc.Iterable[thorchain.v1.x.thorchain.types.type_observed_tx_pb2.ObservedTxVoter] | None = ...,
        tx_outs: collections.abc.Iterable[thorchain.v1.x.thorchain.types.type_tx_out_pb2.TxOut] | None = ...,
        node_accounts: collections.abc.Iterable[thorchain.v1.x.thorchain.types.type_node_account_pb2.NodeAccount] | None = ...,
        vaults: collections.abc.Iterable[thorchain.v1.x.thorchain.types.type_vault_pb2.Vault] | None = ...,
        reserve: builtins.int = ...,
        last_signed_height: builtins.int = ...,
        last_chain_heights: collections.abc.Iterable[global___lastChainHeight] | None = ...,
        reserve_contributors: collections.abc.Iterable[thorchain.v1.x.thorchain.types.type_reserve_contributor_pb2.ReserveContributor] | None = ...,
        network: thorchain.v1.x.thorchain.types.type_network_pb2.Network | None = ...,
        msg_swaps: collections.abc.Iterable[thorchain.v1.x.thorchain.types.msg_swap_pb2.MsgSwap] | None = ...,
        network_fees: collections.abc.Iterable[thorchain.v1.x.thorchain.types.type_network_fee_pb2.NetworkFee] | None = ...,
        chain_contracts: collections.abc.Iterable[thorchain.v1.x.thorchain.types.type_chain_contract_pb2.ChainContract] | None = ...,
        THORNames: collections.abc.Iterable[thorchain.v1.x.thorchain.types.type_thorname_pb2.THORName] | None = ...,
        mimirs: collections.abc.Iterable[global___mimir] | None = ...,
        store_version: builtins.int = ...,
        bond_providers: collections.abc.Iterable[thorchain.v1.x.thorchain.types.type_node_account_pb2.BondProviders] | None = ...,
        POL: thorchain.v1.x.thorchain.types.type_pol_pb2.ProtocolOwnedLiquidity | None = ...,
        loans: collections.abc.Iterable[thorchain.v1.x.thorchain.types.type_loan_pb2.Loan] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["POL", b"POL", "network", b"network"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["POL", b"POL", "THORNames", b"THORNames", "bond_providers", b"bond_providers", "chain_contracts", b"chain_contracts", "last_chain_heights", b"last_chain_heights", "last_signed_height", b"last_signed_height", "liquidity_providers", b"liquidity_providers", "loans", b"loans", "mimirs", b"mimirs", "msg_swaps", b"msg_swaps", "network", b"network", "network_fees", b"network_fees", "node_accounts", b"node_accounts", "observed_tx_in_voters", b"observed_tx_in_voters", "observed_tx_out_voters", b"observed_tx_out_voters", "pools", b"pools", "reserve", b"reserve", "reserve_contributors", b"reserve_contributors", "store_version", b"store_version", "tx_outs", b"tx_outs", "vaults", b"vaults"]) -> None: ...

global___GenesisState = GenesisState
